-- ============================================================
-- Import des 2€ commémoratives 2020 (34 pièces)
-- Aucune édition de la liste blanche cette année-là -> tout sur
-- des lignes génériques (jusqu'à 2 par pays -> 2 lignes).
-- Nécessite fix_and_import_2011_2017.sql déjà exécuté.
-- ============================================================

insert into commemorative_sets (year, name, sort_order) values
  (2020, null, 0),
  (2020, null, 1);

insert into commemorative_coins (set_id, country_id, name, mintage, issue_date, quotation, image_url) values
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='allemagne'), '50e anniversaire de la génuflexion de Willy Brandt à Varsovie', 30000000, 'octobre 2020', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='allemagne'), 'Brandebourg (série consacrée aux Länder)', 30000000, 'février 2020', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='andorre'), '27e Sommet ibéro-américain à Andorre', 73500, 'juin 2020', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='andorre'), '50 ans de suffrage universel pour les femmes', 60000, '2e semestre 2020', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='belgique'), 'Jan van Eyck', 155000, 'mai 2020', 12.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='belgique'), '2020, année internationale de la santé des végétaux', 755000, 'février 2020', 10.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='chypre'), '30e anniversaire de l''Institut chypriote de neurologie et de génétique', 412000, '4e trimestre 2020', 5.0, 'https://monnaies-euros.com/images/2euros_comme_Chypre_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='espagne'), 'Sites inscrits au patrimoine mondial, culturel et naturel de l''UNESCO – Aragon et l''architecture mudéjare d''Aragon', 4000000, 'février 2020', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='estonie'), 'Bicentenaire de la découverte de l''Antarctique', 750000, 'mars 2020', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Estonie2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='estonie'), '100e anniversaire du Traité de Tartu signé le 14 octobre 1920 à Tartu', 1000000, 'février 2020', 3.7, 'https://monnaies-euros.com/images/2euros_comme_Estonie_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='finlande'), 'Universités et société – 100e anniversaire de l''université de Turku', 800000, 'printemps-été 2020', 4.5, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='finlande'), '100e anniversaire de la naissance de Väinö Linna', 800000, '4e trimestre 2020', 4.5, 'https://monnaies-euros.com/images/2euros_comme_Finlande2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='france'), 'Charles de Gaulle', 18061940, 'juin 2020', 2.2, 'https://monnaies-euros.com/images/2euros_comme_France_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='france'), 'Recherche médicale', 300000, 'octobre 2020', 14.0, 'https://monnaies-euros.com/images/2euros_comme_France2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='grece'), '2 500 ans de la bataille des Thermopyles', 750000, 'janvier 2020', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Grece_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='grece'), 'Centenaire de l''union entre la Thrace et la Grèce', 750000, 'mai 2020', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Grece2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='italie'), '80e anniversaire de la fondation du « Corpo Nazionale dei Vigili del Fuoco » (corps national des pompiers)', 3000000, 'janvier 2020', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Italie_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='italie'), '150e anniversaire de la naissance de Maria Montessori', 3000000, 'juin 2020', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Italie2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='lettonie'), 'Céramique du Latgale', 412000, '2e trimestre 2020', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Lettonie_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='lituanie'), 'Haute Lituanie ou « Aukštaitija » en lituanien (série consacrée aux régions ethnographiques de Lituanie)', 500000, 'mars 2020', 3.6, 'https://monnaies-euros.com/images/2euros_comme_Lituanie_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='lituanie'), 'Site du patrimoine culturel de l''UNESCO – Kryžių Kalnas (la Colline des Croix)', 500000, '4e trimestre 2020', 3.6, 'https://monnaies-euros.com/images/2euros_comme_Lituanie2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='luxembourg'), 'Bicentenaire de la naissance du prince Henri', 500000, 'janvier 2020', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='luxembourg'), 'Naissance du prince Charles', 500000, 'décembre 2020', 6.0, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='malte'), 'Jeux d''enfants', 220000, 'octobre 2020', 7.5, 'https://monnaies-euros.com/images/2euros_comme_Malte2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='malte'), 'Patrimoine mondial de l''Unesco – temples préhistoriques de Skorba', 170000, 'mai 2020', 12.0, 'https://monnaies-euros.com/images/2euros_comme_Malte_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='monaco'), '300e anniversaire de la naissance du prince Honoré III', 15000, 'juin 2020', 375.0, 'https://monnaies-euros.com/images/2euros_comme_Monaco_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='portugal'), '75e anniversaire des Nations unies', 510000, 'mai 2020', 3.4, 'https://monnaies-euros.com/images/2euros_comme_Portugal_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='portugal'), '730e anniversaire de l''université de Coimbra', 360000, 'novembre 2020', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Portugal2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='saint-marin'), '500e anniversaire de la mort de Raphaël', 54000, 'mars 2020', 80.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='saint-marin'), '250e anniversaire de la mort de Giambattista Tiepolo', 54000, 'août-septembre 2020', 80.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin2_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='slovaquie'), '20e anniversaire de l''adhésion de la Slovaquie à l''Organisation de Coopération et de Développement Economiques (OCDE)', 1000000, 'novembre 2020', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='slovenie'), '500e anniversaire de la naissance du religieux et écrivain slovène Adam Bohorič', 1000000, '2e semestre 2020', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=0), (select id from countries where slug='vatican'), 'Centenaire de la naissance du pape Jean-Paul II', 101000, 'mai 2020', 45.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2020.webp'),
  ((select id from commemorative_sets where year=2020 and name is null and sort_order=1), (select id from countries where slug='vatican'), '500e anniversaire de la mort de Raphaël', 101000, 'octobre 2020', 40.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican2_2020.webp');
