-- ============================================================
-- Import des 2€ commémoratives 2019 (32 pièces)
-- Aucune édition de la liste blanche cette année-là -> tout sur
-- des lignes génériques (jusqu'à 2 par pays -> 2 lignes).
-- Nécessite fix_and_import_2011_2017.sql déjà exécuté.
-- ============================================================

insert into commemorative_sets (year, name, sort_order) values
  (2019, null, 0),
  (2019, null, 1);

insert into commemorative_coins (set_id, country_id, name, mintage, issue_date, quotation, image_url) values
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='allemagne'), '70e anniversaire de la fondation du Bundesrat', 30000000, 'janvier 2019', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne2_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=1), (select id from countries where slug='allemagne'), '30e anniversaire de la chute du mur de Berlin', 30000000, 'septembre/octobre 2019', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='andorre'), '600 ans du conseil de la Terre', 60000, '4e trimestre 2019', 45.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre2_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=1), (select id from countries where slug='andorre'), 'Finale de la Coupe du monde de ski de 2019', 60000, 'mars 2019', 80.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='belgique'), '25e anniversaire de l''Institut monétaire européen (IME)', 155000, 'janvier 2019', 12.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique2_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=1), (select id from countries where slug='belgique'), '450e anniversaire de Pieter Bruegel l''Ancien', 155000, 'janvier 2019', 12.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='espagne'), 'La vieille ville d''Ávila et ses églises extra-muros', 1000000, 'février 2019', 4.5, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='estonie'), '150e anniversaire du Festival de chant', 1000000, 'juin 2019', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Estonie_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=1), (select id from countries where slug='estonie'), '100e anniversaire de l''université de Tartu', 1000000, 'novembre 2019', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Estonie2_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='finlande'), 'La constitution finlandaise', 500000, 'septembre/octobre 2019', 28.0, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='france'), '30e anniversaire de la chute du mur de Berlin', 10000000, 'octobre 2019', 2.2, 'https://monnaies-euros.com/images/2euros_comme_France_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=1), (select id from countries where slug='france'), '60e anniversaire d''Astérix', 310000, 'mai 2019', 30.0, 'https://monnaies-euros.com/images/2euros_comme_France2_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='grece'), '100e anniversaire de la naissance de Manolis Andronicos', 750000, 'juin 2019', 3.6, 'https://monnaies-euros.com/images/2euros_comme_Grece2_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=1), (select id from countries where slug='grece'), '150e anniversaire de la mort d''Andreas Kalvos', 750000, 'juin 2019', 3.6, 'https://monnaies-euros.com/images/2euros_comme_Grece_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='irlande'), '100e anniversaire de la création du Dáil Éireann', 1000000, 'janvier 2019', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Irlande_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='italie'), '500e anniversaire de la mort de Léonard de Vinci', 3000000, 'janvier 2019', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Italie_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='lettonie'), 'Lever de soleil', 307000, '3e trimestre 2019', 5.5, 'https://monnaies-euros.com/images/2euros_comme_Lettonie_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='lituanie'), 'La Samogitie (région ethnographique de Lituanie)', 500000, '3e trimestre 2019', 3.7, 'https://monnaies-euros.com/images/2euros_comme_Lituanie2_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=1), (select id from countries where slug='lituanie'), 'Les Sutartinės (chants polyphoniques lituaniens)', 500000, '3e trimestre 2019', 3.7, 'https://monnaies-euros.com/images/2euros_comme_Lituanie_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='luxembourg'), '100e anniversaire de l''accession au trône de la Grande-Duchesse Charlotte', 500000, 'janvier 2019', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=1), (select id from countries where slug='luxembourg'), '100e anniversaire du suffrage universel', 500000, 'septembre 2019', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg2_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='malte'), 'Temples préhistoriques de Ta'' Haġrat', 320000, 'juillet 2019', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Malte2_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=1), (select id from countries where slug='malte'), 'Nature et environnement', 320000, '21 octobre 2019', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Malte_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='monaco'), '200e anniversaire de l''accession au trône du prince Honoré V', 15000, 'juin 2019', 400.0, 'https://monnaies-euros.com/images/2euros_comme_Monaco_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='portugal'), '500e anniversaire de la première circumnavigation, organisée et menée par l''explorateur et navigateur portugais Fernão de Magalhães (Fernand de Magellan)', 750000, '2e trimestre 2019', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Portugal2_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=1), (select id from countries where slug='portugal'), '600e anniversaire de la découverte de l''archipel de Madère par les navigateurs portugais Bartolomeu Perestrelo et Tristão Vaz', 500000, '2e trimestre 2019', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Portugal_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='saint-marin'), '550e anniversaire de la mort de Filippo Lippi', 60500, 'septembre 2019', 90.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=1), (select id from countries where slug='saint-marin'), '500e anniversaire de la mort de Léonard de Vinci', 60500, 'avril 2019', 90.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin2_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='slovaquie'), '100e anniversaire de la mort de Milan Rastislav Štefánik', 1000000, 'avril 2019', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='slovenie'), '100e anniversaire de la fondation de l''Université de Ljubljana', 1000000, '4e trimestre 2019', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=0), (select id from countries where slug='vatican'), '90e anniversaire de la création de l''État de la Cité du Vatican', 91000, 'mars 2019', 40.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican2_2019.webp'),
  ((select id from commemorative_sets where year=2019 and name is null and sort_order=1), (select id from countries where slug='vatican'), 'Fin de la restauration de la chapelle Sixtine – 1994-2019', 91000, '1er octobre 2019', 40.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2019.webp');
