-- ============================================================
-- Import des 2€ commémoratives 2017 (32 pièces)
-- Aucune édition de la liste blanche cette année-là -> tout sur
-- la ligne générique 2017.
-- À exécuter après reset_commemoratives.sql + imports précédents.
-- ============================================================
insert into commemorative_sets (year, name, sort_order) values
  (2017, null, 0)
on conflict (year) where name is null do nothing;

insert into commemorative_coins (set_id, country_id, name, mintage, issue_date, quotation, image_url) values
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='allemagne'), 'Rhénanie-Palatinat', 30000000, 'février 2017', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='andorre'), 'Andorre – Le pays des Pyrénées', 85000, 'décembre 2017', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='andorre'), 'centenaire de l''hymne d''Andorre', 85000, 'décembre 2017', 19.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre2_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='belgique'), '200e anniversaire de l''université de Gand', 200000, 'septembre 2017', 11.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='belgique'), '200e anniversaire de l''université de Liège', 200000, 'avril 2017', 11.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique2_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='chypre'), 'Paphos 2017 – Capitale européenne de la Culture', 430000, 'septembre 2017', 5.0, 'https://monnaies-euros.com/images/2euros_comme_Chypre_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='espagne'), 'Églises du royaume des Asturies', 4000000, 'février 2017', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='estonie'), 'Indépendance de l''Estonie', 1500000, 'juillet 2017', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Estonie_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='finlande'), 'La nature finlandaise', 500000, 'octobre 2017', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='finlande'), '100e anniversaire de l''indépendance de la Finlande', 2500000, 'avril 2017', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Finlande2_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='france'), '25e anniversaire du ruban rose, symbole de la lutte contre le cancer du sein', 10000000, 'septembre 2017', 2.3, 'https://monnaies-euros.com/images/2euros_comme_France_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='france'), 'Centenaire de la mort d''Auguste Rodin', 10000000, 'janvier 2017', 2.3, 'https://monnaies-euros.com/images/2euros_comme_France2_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='grece'), '60e anniversaire de la mort de Nikos Kazantzakis', 750000, 'juillet 2017', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Grece_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='grece'), 'Site archéologique de Philippes', 750000, 'juillet 2017', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Grece2_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='italie'), 'Bimillénaire de la mort de Tite-Live', 1500000, 'avril 2017', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Italie_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='italie'), '400e anniversaire de l''achèvement de la basilique Saint-Marc à Venise', 1500000, 'janvier 2017', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Italie2_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='lettonie'), 'Latgale', 530000, 'octobre 2017', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Lettonie_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='lettonie'), 'Kurzeme', 530000, 'septembre 2017', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Lettonie2_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='lituanie'), 'Vilnius', 1000000, 'juillet 2017', 3.6, 'https://monnaies-euros.com/images/2euros_comme_Lituanie_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='luxembourg'), '200e anniversaire de la naissance du Grand-Duc Guillaume III', 500000, 'octobre 2017', 3.9, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='luxembourg'), '50e anniversaire du volontariat auprès de l''armée luxembourgeoise', 500000, 'janvier 2017', 3.9, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg2_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='malte'), 'Solidarité et paix', 380000, 'novembre 2017', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Malte_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='malte'), 'Temples préhistoriques maltais de Hagar Qim', 405000, 'juin 2017', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Malte2_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='monaco'), 'Carabiniers du Prince', 15000, 'novembre 2017', 700.0, 'https://monnaies-euros.com/images/2euros_comme_Monaco_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='portugal'), '150 ans de la naissance de l''écrivain Raul Brandão', 520000, 'novembre 2017', 3.7, 'https://monnaies-euros.com/images/2euros_comme_Portugal_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='portugal'), '150e anniversaire de la police de sécurité publique', 520000, 'juillet 2017', 3.7, 'https://monnaies-euros.com/images/2euros_comme_Portugal2_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='saint-marin'), 'Année internationale du tourisme durable pour le développement', 70500, 'septembre 2017', 38.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='saint-marin'), '750e anniversaire de la naissance de Giotto', 80000, 'mars 2017', 35.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin2_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='slovaquie'), '550e anniversaire de l''Académie istropolitaine', 1000000, 'janvier 2017', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='slovenie'), '10e anniversaire de l''euro en Slovénie', 1000000, 'janvier 2017', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='vatican'), '100e anniversaire des apparitions de Fatima', 105000, 'octobre 2017', 40.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2017.webp'),
  ((select id from commemorative_sets where year=2017 and name is null), (select id from countries where slug='vatican'), '1950e anniversaire du martyre de saint Pierre et de saint Paul', 105000, 'juin 2017', 40.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican2_2017.webp')
on conflict (set_id, country_id) do nothing;
