-- ============================================================
-- Import des 2€ commémoratives 2025 (36 pièces)
-- Aucune édition de la liste blanche cette année-là -> tout sur
-- des lignes génériques. Vatican a 3 pièces distinctes cette
-- année (Michel-Ange, Sede vacante, Jubilé) -> 3 lignes génériques
-- nécessaires, test du modèle multi-slots.
-- Nécessite fix_and_import_2011_2017.sql déjà exécuté.
-- ============================================================

insert into commemorative_sets (year, name, sort_order) values
  (2025, null, 0),
  (2025, null, 1),
  (2025, null, 2);

insert into commemorative_coins (set_id, country_id, name, mintage, issue_date, quotation, image_url) values
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='allemagne'), '35 ans de l''unité allemande', 30000000, '25 septembre 2025', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='allemagne'), 'État fédéral (Land) de Sarre', 30000000, 'janvier 2025', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='andorre'), 'Jeux des petits États d''Europe organisés en Andorre', 64000, '2e semestre 2025', 24.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='andorre'), 'Gypaète barbu', 60000, '2e semestre 2025', 25.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='belgique'), 'Loterie nationale de Belgique', 1000000, 'janvier 2025', 12.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='belgique'), 'Circuit automobile de Spa-Francorchamps en Belgique', 155000, 'juillet 2025', 13.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='croatie'), 'Série des villes croates — Grad Pula — Arène', 200000, 'octobre 2025', 21.0, 'https://monnaies-euros.com/images/2euros_comme_Croatie2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='croatie'), '1100e anniversaire du Royaume de Croatie et du couronnement du roi Tomislav', 400000, 'juillet 2025', 7.0, 'https://monnaies-euros.com/images/2euros_comme_Croatie_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='espagne'), 'Inscription de Salamanque au patrimoine mondial de l''Unesco', 2000000, '1er trimestre 2025', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='estonie'), '500e anniversaire de la naissance de la langue littéraire estonienne', 850000, '2e trimestre 2025', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Estonie_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='finlande'), 'Compétition d''athlétisme finno-suédoise', 204000, 'automne 2025', 15.0, 'https://monnaies-euros.com/images/2euros_comme_Finlande2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='finlande'), 'Visites d''État finlandaises - diplomatie et politique étrangère', 204000, 'printemps 2025', 11.0, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='france'), 'Notre Dame de Paris', 20000000, 'septembre 2025', 2.5, 'https://monnaies-euros.com/images/2euros_comme_France2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='france'), 'Musée du Louvre', 315000, 'janvier 2025', 12.0, 'https://monnaies-euros.com/images/2euros_comme_France_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='grece'), 'Bicentenaire de la mort de Laskarina Bouboulina', 750000, 'juillet 2025', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Grece_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='grece'), '100e anniversaire de la naissance de Mikis Theodorakis', 750000, 'juillet 2025', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Grece2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='italie'), 'Tour du monde de l''Amerigo Vespucci 2023-2025', 3000000, 'janvier 2025', 2.7, 'https://monnaies-euros.com/images/2euros_comme_Italie_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='italie'), 'Jubilé 2025', 3000000, 'janvier 2025', 2.7, 'https://monnaies-euros.com/images/2euros_comme_Italie2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='lettonie'), 'Sélonie (Sēlija)', 413000, '9 octobre 2025', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Lettonie_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='lituanie'), 'Régions ethnographiques lituaniennes — Petite Lituanie', 500000, '4e trimestre 2025', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Lituanie2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='lituanie'), 'Défense', 500000, '1er trimestre 2025', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Lituanie_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='luxembourg'), '75e anniversaire de la déclaration de Robert Schuman du 9 mai 1950', 200000, 'février 2025', 9.5, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='luxembourg'), '25e anniversaire de l''accession au trône du Grand-Duc Henri', 200000, 'février 2025', 9.5, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='malte'), 'Ville de Mdina', 152000, 'juin 2025', 15.0, 'https://monnaies-euros.com/images/2euros_comme_Malte2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='malte'), 'Bœuf maltais (il-gendus Malti)', 145000, 'juin 2025', 15.0, 'https://monnaies-euros.com/images/2euros_comme_Malte_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='monaco'), 'Comté de Carladès', 15000, 'juin 2025', 260.0, 'https://monnaies-euros.com/images/2euros_comme_Monaco_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='monaco'), 'Marquisat des Baux', 15000, 'novembre 2025', 210.0, 'https://monnaies-euros.com/images/2euros_comme_Monaco2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='portugal'), 'Développement durable', 500000, '1er trimestre 2025', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Portugal_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='portugal'), 'Scoutisme mondial', 500000, 'juin 2025', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Portugal2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='saint-marin'), '550e anniversaire de la naissance de Michel-Ange', 56000, 'juillet 2025', 34.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin2_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='saint-marin'), 'Giubileo Anno Santo 2025 - Pellegrini di Speranza', 56000, 'mars 2025', 34.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='slovaquie'), '100e anniversaire de la première compétition sportive internationale organisée sur le territoire de la République slovaque – le championnat d''Europe de hockey sur glace', 1000000, 'janvier 2025', 2.7, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='slovenie'), '100e anniversaire de la naissance de Miki Muster', 1000000, 'novembre 2025', 3.1, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=0), (select id from countries where slug='vatican'), '550e anniversaire de la naissance de Michel-Ange', 80000, 'juin 2025', 85.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=1), (select id from countries where slug='vatican'), 'Sede vacante 2025', 76000, 'juin 2025', 90.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican3_2025.webp'),
  ((select id from commemorative_sets where year=2025 and name is null and sort_order=2), (select id from countries where slug='vatican'), 'Jubilé 2025', 91000, 'juin 2025', 85.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican2_2025.webp');
