-- ============================================================
-- Import des 2€ commémoratives 2004-2010, structure par SETS
-- (un set = année + raison ; un pays peut avoir plusieurs sets la
--  même année ; un set commun regroupe plusieurs pays sur 1 ligne)
-- Source : https://monnaies-euros.com/euro2commemorative{annee}.php
-- Nécessite migrate_commemorative_sets.sql exécuté AVANT ce fichier,
-- et import_sets.sql (pays) déjà en place.
-- ============================================================

-- 1) Sets (année + raison)
insert into commemorative_sets (year, name, sort_order) values
  (2004, 'Elargissement de l''Union européenne à dix nouveaux États membres', 0),
  (2004, 'Jeux olympiques d''Athènes de 2004', 1),
  (2004, '50ème anniversaire du Programme alimentaire mondial', 2),
  (2004, 'Effigie et monogramme du Grand-Duc Henri', 3),
  (2004, 'Bartolomeo Borghesi (historien, numismate)', 4),
  (2004, '75ème anniversaire de la fondation de l''État de la Cité du Vatican', 5),
  (2005, '50e anniversaire du Traité d''État autrichien', 0),
  (2005, 'Union économique belgo-luxembourgeoise', 1),
  (2005, '4e centenaire de la première édition de « L''ingénieux hidalgo Don Quichotte de la Manche » de Miguel de Cervantes', 2),
  (2005, '60e anniversaire des Nations unies et 50e anniversaire de l''adhésion de la Finlande aux Nations unies', 3),
  (2005, '1er anniversaire de la signature de la Constitution européenne', 4),
  (2005, '50e anniversaire du Grand-Duc Henri, 5e anniversaire de son accession au trône et centenaire de la mort du Grand-Duc Adolphe', 5),
  (2005, '2005, année mondiale de la physique', 6),
  (2005, '20e Journées mondiales de la jeunesse', 7),
  (2006, 'Schleswig-Holstein', 0),
  (2006, 'Atomium', 1),
  (2006, '100e anniversaire du suffrage universel et égalitaire', 2),
  (2006, 'XXe Jeux olympiques d''hiver - Turin 2006', 3),
  (2006, '25e anniversaire de l''héritier du trône, le Grand-Duc Guillaume', 4),
  (2006, '500e anniversaire de la mort de Christophe Colomb', 5),
  (2006, '5e centenaire de la Garde suisse pontificale', 6),
  (2007, '50ème anniversaire du traité de Rome', 0),
  (2007, 'Mecklembourg-Poméranie occidentale', 1),
  (2007, '90ème anniversaire de l''indépendance de la Finlande', 2),
  (2007, 'Palais grand-ducal', 3),
  (2007, '25ème anniversaire de la mort de la Princesse Grace', 4),
  (2007, 'Présidence portugaise de l''Union européenne', 5),
  (2007, 'Bicentenaire de la naissance de Giuseppe Garibaldi', 6),
  (2007, '80ème anniversaire de Sa Sainteté le pape Benoît XVI', 7),
  (2008, 'État fédéré de Hambourg', 0),
  (2008, '60e anniversaire de la Déclaration Universelle des Droits de l''Homme', 1),
  (2008, 'Présidence française du Conseil de l''Union européenne au deuxie semestre 2008', 2),
  (2008, 'Grand-Duc Henri et château de Berg', 3),
  (2008, 'Année européenne du Dialogue interculturel', 4),
  (2008, '500e anniversaire de la naissance de Primož Trubar', 5),
  (2008, 'Année de saint Paul – bimillénaire de sa naissance', 6),
  (2009, '10ème anniversaire de l''Union économique et monétaire', 0),
  (2009, 'État fédéré de la Sarre', 1),
  (2009, 'Bicentenaire de la naissance de Louis Braille', 2),
  (2009, '200ème anniversaire de l''autonomie de la Finlande et de la Diète de Porvoo', 3),
  (2009, 'Grand-Duc Henri et Grande-Duchesse Charlotte', 4),
  (2009, 'Deuxième Jeux de la Lusophonie', 5),
  (2009, 'Année européenne de la créativité et de l''innovation', 6),
  (2009, '20ème anniversaire du jour de la liberté et de la démocratie (17 novembre 1989)', 7),
  (2009, 'Année internationale de l''Astronomie', 8),
  (2010, 'État fédéré de Brême', 0),
  (2010, 'Présidence belge du Conseil de l''Union européenne en 2010', 1),
  (2010, 'Centre historique de Cordoue – liste de l''héritage mondial de l''Unesco', 2),
  (2010, 'Décret monétaire de 1860 autorisant la Finlande à émettre des billets de banque et des pièces', 3),
  (2010, '70e anniversaire de l''Appel du 18 juin', 4),
  (2010, '2 500e anniversaire de la bataille de Marathon', 5),
  (2010, 'Bicentenaire de la naissance du comte de Cavour', 6),
  (2010, 'Les armoiries du Grand-Duc', 7),
  (2010, 'Centenaire de la République portugaise', 8),
  (2010, '500e anniversaire de la mort de Sandro Botticelli', 9),
  (2010, '200e anniversaire du jardin botanique de Ljubljana', 10),
  (2010, 'Année des prêtres', 11)
on conflict (year, name) do nothing;

-- 2) Pièces (une ligne par pays ayant émis ce design)
insert into commemorative_coins (set_id, country_id, mintage, issue_date, quotation, image_url) values
  ((select id from commemorative_sets where year=2004 and name='Elargissement de l''Union européenne à dix nouveaux États membres'), (select id from countries where slug='finlande'), 1000000, 'juin 2004', 40.0, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2004.webp'),
  ((select id from commemorative_sets where year=2004 and name='Jeux olympiques d''Athènes de 2004'), (select id from countries where slug='grece'), 50000000, 'mars 2004', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Grece_2004.webp'),
  ((select id from commemorative_sets where year=2004 and name='50ème anniversaire du Programme alimentaire mondial'), (select id from countries where slug='italie'), 16000000, 'décembre 2004', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Italie_2004.webp'),
  ((select id from commemorative_sets where year=2004 and name='Effigie et monogramme du Grand-Duc Henri'), (select id from countries where slug='luxembourg'), 2490000, 'juin 2004', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2004.webp'),
  ((select id from commemorative_sets where year=2004 and name='Bartolomeo Borghesi (historien, numismate)'), (select id from countries where slug='saint-marin'), 110000, 'décembre 2004', 145.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2004.webp'),
  ((select id from commemorative_sets where year=2004 and name='75ème anniversaire de la fondation de l''État de la Cité du Vatican'), (select id from countries where slug='vatican'), 100000, 'décembre 2004', 125.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2004.webp'),
  ((select id from commemorative_sets where year=2005 and name='50e anniversaire du Traité d''État autrichien'), (select id from countries where slug='autriche'), 7000000, 'mai 2005', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Autriche_2005.webp'),
  ((select id from commemorative_sets where year=2005 and name='Union économique belgo-luxembourgeoise'), (select id from countries where slug='belgique'), 6000000, 'mars 2005', 4.5, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2005.webp'),
  ((select id from commemorative_sets where year=2005 and name='4e centenaire de la première édition de « L''ingénieux hidalgo Don Quichotte de la Manche » de Miguel de Cervantes'), (select id from countries where slug='espagne'), 8000000, 'avril 2005', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2005.webp'),
  ((select id from commemorative_sets where year=2005 and name='60e anniversaire des Nations unies et 50e anniversaire de l''adhésion de la Finlande aux Nations unies'), (select id from countries where slug='finlande'), 2000000, 'octobre 2005', 5.0, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2005.webp'),
  ((select id from commemorative_sets where year=2005 and name='1er anniversaire de la signature de la Constitution européenne'), (select id from countries where slug='italie'), 18000000, 'octobre 2005', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Italie_2005.webp'),
  ((select id from commemorative_sets where year=2005 and name='50e anniversaire du Grand-Duc Henri, 5e anniversaire de son accession au trône et centenaire de la mort du Grand-Duc Adolphe'), (select id from countries where slug='luxembourg'), 2800000, 'janvier 2005', 3.9, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2005.webp'),
  ((select id from commemorative_sets where year=2005 and name='2005, année mondiale de la physique'), (select id from countries where slug='saint-marin'), 130000, 'octobre 2005', 105.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2005.webp'),
  ((select id from commemorative_sets where year=2005 and name='20e Journées mondiales de la jeunesse'), (select id from countries where slug='vatican'), 100000, 'décembre 2005', 200.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2005.webp'),
  ((select id from commemorative_sets where year=2006 and name='Schleswig-Holstein'), (select id from countries where slug='allemagne'), 30000000, 'février 2006', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2006.webp'),
  ((select id from commemorative_sets where year=2006 and name='Atomium'), (select id from countries where slug='belgique'), 5000000, 'avril 2006', 4.5, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2006.webp'),
  ((select id from commemorative_sets where year=2006 and name='100e anniversaire du suffrage universel et égalitaire'), (select id from countries where slug='finlande'), 2500000, 'octobre 2006', 4.8, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2006.webp'),
  ((select id from commemorative_sets where year=2006 and name='XXe Jeux olympiques d''hiver - Turin 2006'), (select id from countries where slug='italie'), 40000000, 'janvier 2006', 2.5, 'https://monnaies-euros.com/images/2euros_comme_Italie_2006.webp'),
  ((select id from commemorative_sets where year=2006 and name='25e anniversaire de l''héritier du trône, le Grand-Duc Guillaume'), (select id from countries where slug='luxembourg'), 1100000, 'janvier 2006', 4.2, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2006.webp'),
  ((select id from commemorative_sets where year=2006 and name='500e anniversaire de la mort de Christophe Colomb'), (select id from countries where slug='saint-marin'), 120000, 'octobre 2006', 100.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2006.webp'),
  ((select id from commemorative_sets where year=2006 and name='5e centenaire de la Garde suisse pontificale'), (select id from countries where slug='vatican'), 100000, 'novembre 2006', 180.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2006.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='allemagne'), 30865630, 'mars 2007', 2.2, 'https://monnaies-euros.com/images/2euros_comme2_Allemagne_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='Mecklembourg-Poméranie occidentale'), (select id from countries where slug='allemagne'), 30000000, 'février 2007', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='autriche'), 9000000, 'mars 2007', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Autriche_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='belgique'), 5040000, 'mars 2007', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='espagne'), 8000000, 'mars 2007', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='90ème anniversaire de l''indépendance de la Finlande'), (select id from countries where slug='finlande'), 2000000, 'décembre 2007', 4.2, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='finlande'), 1400000, 'mars 2007', 4.5, 'https://monnaies-euros.com/images/2euros_comme2_Finlande_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='france'), 9406875, 'mars 2007', 2.5, 'https://monnaies-euros.com/images/2euros_comme_France_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='grece'), 3978549, 'mars 2007', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Grece_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='irlande'), 4640112, 'mars 2007', 3.4, 'https://monnaies-euros.com/images/2euros_comme_Irlande_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='italie'), 5000000, 'mars 2007', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Italie_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='Palais grand-ducal'), (select id from countries where slug='luxembourg'), 1100000, 'février 2007', 4.1, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='luxembourg'), 2046000, 'mars 2007', 3.8, 'https://monnaies-euros.com/images/2euros_comme2_Luxembourg_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='25ème anniversaire de la mort de la Princesse Grace'), (select id from countries where slug='monaco'), 20000, 'juillet 2007', 2000.0, 'https://monnaies-euros.com/images/2euros_comme_Monaco_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='pays-bas'), 6355500, 'mars 2007', 3.4, 'https://monnaies-euros.com/images/2euros_comme_PaysBas_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='Présidence portugaise de l''Union européenne'), (select id from countries where slug='portugal'), 2000000, 'juillet 2007', 4.5, 'https://monnaies-euros.com/images/2euros_comme_Portugal_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='portugal'), 1520000, 'mars 2007', 4.2, 'https://monnaies-euros.com/images/2euros_comme2_Portugal_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='Bicentenaire de la naissance de Giuseppe Garibaldi'), (select id from countries where slug='saint-marin'), 130000, 'octobre 2007', 45.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='50ème anniversaire du traité de Rome'), (select id from countries where slug='slovenie'), 400000, 'mars 2007', 25.0, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2007.webp'),
  ((select id from commemorative_sets where year=2007 and name='80ème anniversaire de Sa Sainteté le pape Benoît XVI'), (select id from countries where slug='vatican'), 100000, 'octobre 2007', 140.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2007.webp'),
  ((select id from commemorative_sets where year=2008 and name='État fédéré de Hambourg'), (select id from countries where slug='allemagne'), 30000000, 'février 2008', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2008.webp'),
  ((select id from commemorative_sets where year=2008 and name='60e anniversaire de la Déclaration Universelle des Droits de l''Homme'), (select id from countries where slug='belgique'), 5000000, 'mai 2008', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2008.webp'),
  ((select id from commemorative_sets where year=2008 and name='60e anniversaire de la Déclaration Universelle des Droits de l''Homme'), (select id from countries where slug='finlande'), 1500000, 'octobre 2008', 4.5, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2008.webp'),
  ((select id from commemorative_sets where year=2008 and name='Présidence française du Conseil de l''Union européenne au deuxie semestre 2008'), (select id from countries where slug='france'), 20000000, 'juillet 2008', 2.5, 'https://monnaies-euros.com/images/2euros_comme_France_2008.webp'),
  ((select id from commemorative_sets where year=2008 and name='60e anniversaire de la Déclaration Universelle des Droits de l''Homme'), (select id from countries where slug='italie'), 5000000, 'avril 2008', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Italie_2008.webp'),
  ((select id from commemorative_sets where year=2008 and name='Grand-Duc Henri et château de Berg'), (select id from countries where slug='luxembourg'), 1300000, 'février 2008', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2008.webp'),
  ((select id from commemorative_sets where year=2008 and name='60e anniversaire de la Déclaration Universelle des Droits de l''Homme'), (select id from countries where slug='portugal'), 1000000, 'septembre 2008', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Portugal_2008.webp'),
  ((select id from commemorative_sets where year=2008 and name='Année européenne du Dialogue interculturel'), (select id from countries where slug='saint-marin'), 130000, 'avril 2008', 80.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2008.webp'),
  ((select id from commemorative_sets where year=2008 and name='500e anniversaire de la naissance de Primož Trubar'), (select id from countries where slug='slovenie'), 1000000, 'mai 2008', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2008.webp'),
  ((select id from commemorative_sets where year=2008 and name='Année de saint Paul – bimillénaire de sa naissance'), (select id from countries where slug='vatican'), 100000, 'octobre 2008', 55.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2008.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='allemagne'), 30565630, 'janvier 2009', 2.2, 'https://monnaies-euros.com/images/2euros_comme2_Allemagne_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='État fédéré de la Sarre'), (select id from countries where slug='allemagne'), 30000000, 'février 2009', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='autriche'), 5000000, 'janvier 2009', 3.1, 'https://monnaies-euros.com/images/2euros_comme_Autriche_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='Bicentenaire de la naissance de Louis Braille'), (select id from countries where slug='belgique'), 5000000, 'septembre 2009', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='belgique'), 5012000, 'janvier 2009', 3.5, 'https://monnaies-euros.com/images/2euros_comme2_Belgique_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='chypre'), 1000000, 'janvier 2009', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Chypre_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='espagne'), 8000000, 'janvier 2009', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='finlande'), 1400000, 'janvier 2009', 4.2, 'https://monnaies-euros.com/images/2euros_comme2_Finlande_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='200ème anniversaire de l''autonomie de la Finlande et de la Diète de Porvoo'), (select id from countries where slug='finlande'), 1600000, 'octobre 2009', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='france'), 10074085, 'janvier 2009', 2.5, 'https://monnaies-euros.com/images/2euros_comme_France_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='grece'), 4000000, 'janvier 2009', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Grece_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='irlande'), 5000000, 'janvier 2009', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Irlande_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='Bicentenaire de la naissance de Louis Braille'), (select id from countries where slug='italie'), 2000000, 'octobre 2009', 3.4, 'https://monnaies-euros.com/images/2euros_comme_Italie_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='italie'), 2000000, 'janvier 2009', 3.4, 'https://monnaies-euros.com/images/2euros_comme2_Italie_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='Grand-Duc Henri et Grande-Duchesse Charlotte'), (select id from countries where slug='luxembourg'), 1400000, 'janvier 2009', 3.9, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='luxembourg'), 825000, 'janvier 2009', 4.2, 'https://monnaies-euros.com/images/2euros_comme2_Luxembourg_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='malte'), 700000, 'janvier 2009', 4.5, 'https://monnaies-euros.com/images/2euros_comme_Malte_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='pays-bas'), 5313500, 'janvier 2009', 3.3, 'https://monnaies-euros.com/images/2euros_comme_PaysBas_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='Deuxième Jeux de la Lusophonie'), (select id from countries where slug='portugal'), 1250000, 'juin 2009', 3.9, 'https://monnaies-euros.com/images/2euros_comme_Portugal_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='portugal'), 1285000, 'janvier 2009', 3.9, 'https://monnaies-euros.com/images/2euros_comme2_Portugal_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='Année européenne de la créativité et de l''innovation'), (select id from countries where slug='saint-marin'), 130000, 'mai 2009', 40.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='20ème anniversaire du jour de la liberté et de la démocratie (17 novembre 1989)'), (select id from countries where slug='slovaquie'), 1000000, 'novembre 2009', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='slovaquie'), 2500000, 'janvier 2009', 3.0, 'https://monnaies-euros.com/images/2euros_comme2_Slovaquie_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='10ème anniversaire de l''Union économique et monétaire'), (select id from countries where slug='slovenie'), 1000000, 'janvier 2009', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2009.webp'),
  ((select id from commemorative_sets where year=2009 and name='Année internationale de l''Astronomie'), (select id from countries where slug='vatican'), 106000, 'octobre 2009', 50.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2009.webp'),
  ((select id from commemorative_sets where year=2010 and name='État fédéré de Brême'), (select id from countries where slug='allemagne'), 30000000, 'janvier 2010', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2010.webp'),
  ((select id from commemorative_sets where year=2010 and name='Présidence belge du Conseil de l''Union européenne en 2010'), (select id from countries where slug='belgique'), 5000000, 'juin 2010', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2010.webp'),
  ((select id from commemorative_sets where year=2010 and name='Centre historique de Cordoue – liste de l''héritage mondial de l''Unesco'), (select id from countries where slug='espagne'), 8000000, 'mars 2010', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2010.webp'),
  ((select id from commemorative_sets where year=2010 and name='Décret monétaire de 1860 autorisant la Finlande à émettre des billets de banque et des pièces'), (select id from countries where slug='finlande'), 1600000, 'octobre 2010', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2010.webp'),
  ((select id from commemorative_sets where year=2010 and name='70e anniversaire de l''Appel du 18 juin'), (select id from countries where slug='france'), 20000000, 'juin 2010', 2.5, 'https://monnaies-euros.com/images/2euros_comme_France_2010.webp'),
  ((select id from commemorative_sets where year=2010 and name='2 500e anniversaire de la bataille de Marathon'), (select id from countries where slug='grece'), 2500000, 'octobre 2010', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Grece_2010.webp'),
  ((select id from commemorative_sets where year=2010 and name='Bicentenaire de la naissance du comte de Cavour'), (select id from countries where slug='italie'), 4000000, 'mars 2010', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Italie_2010.webp'),
  ((select id from commemorative_sets where year=2010 and name='Les armoiries du Grand-Duc'), (select id from countries where slug='luxembourg'), 1000000, 'janvier 2010', 3.9, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2010.webp'),
  ((select id from commemorative_sets where year=2010 and name='Centenaire de la République portugaise'), (select id from countries where slug='portugal'), 2000000, 'septembre 2010', 3.9, 'https://monnaies-euros.com/images/2euros_comme_Portugal_2010.webp'),
  ((select id from commemorative_sets where year=2010 and name='500e anniversaire de la mort de Sandro Botticelli'), (select id from countries where slug='saint-marin'), 130000, 'septembre 2010', 40.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2010.webp'),
  ((select id from commemorative_sets where year=2010 and name='200e anniversaire du jardin botanique de Ljubljana'), (select id from countries where slug='slovenie'), 1000000, 'mai 2010', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2010.webp'),
  ((select id from commemorative_sets where year=2010 and name='Année des prêtres'), (select id from countries where slug='vatican'), 115000, 'octobre 2010', 45.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2010.webp');
