-- ============================================================
-- Import des 2€ commémoratives 2022 (49 pièces)
-- Édition commune de la liste blanche : "35 ans du programme
-- Erasmus" (19 pays) -> 1 ligne dédiée. Le reste sur des lignes
-- génériques (jusqu'à 3 par pays -> 3 lignes, ex: Italie/Espagne).
-- Nécessite fix_and_import_2011_2017.sql déjà exécuté.
-- ============================================================

insert into commemorative_sets (year, name, sort_order) values
  (2022, '35 ans du programme Erasmus', 1000);

insert into commemorative_sets (year, name, sort_order) values
  (2022, null, 0),
  (2022, null, 1);

insert into commemorative_coins (set_id, country_id, name, mintage, issue_date, quotation, image_url) values
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='allemagne'), '35 ans du programme Erasmus', 20000000, '1er juillet 2022', 2.3, 'https://monnaies-euros.com/images/2euros_comme_Allemagne2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='autriche'), '35 ans du programme Erasmus', 1000000, '1er juillet 2022', 3.1, 'https://monnaies-euros.com/images/2euros_comme_Autriche_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='belgique'), '35 ans du programme Erasmus', 100000, '2022', 12.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='chypre'), '35 ans du programme Erasmus', 350000, '1er juillet 2022', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Chypre_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='espagne'), '35 ans du programme Erasmus', 1000000, '1er juillet 2022', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Espagne3_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='estonie'), '35 ans du programme Erasmus', 988000, '1er juillet 2022', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Estonie3_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='finlande'), '35 ans du programme Erasmus', 800000, '1er juillet 2022', 4.2, 'https://monnaies-euros.com/images/2euros_comme_Finlande3_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='france'), '35 ans du programme Erasmus', 3500000, '1er juillet 2022', 2.5, 'https://monnaies-euros.com/images/2euros_comme_France3_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='grece'), '35 ans du programme Erasmus', 745500, '1er juillet 2022', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Grece2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='irlande'), '35 ans du programme Erasmus', 500000, '1er juillet 2022', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Irlande_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='italie'), '35 ans du programme Erasmus', 3000000, '1er juillet 2022', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Italie3_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='lettonie'), '35 ans du programme Erasmus', 307000, '1er juillet 2022', 5.0, 'https://monnaies-euros.com/images/2euros_comme_Lettonie2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='lituanie'), '35 ans du programme Erasmus', 300000, '1er juillet 2022', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Lituanie3_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='luxembourg'), '35 ans du programme Erasmus', 250000, '1er juillet 2022', 6.0, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg3_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='malte'), '35 ans du programme Erasmus', 62500, '1er juillet 2022', 50.0, 'https://monnaies-euros.com/images/2euros_comme_Malte3_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='pays-bas'), '35 ans du programme Erasmus', 500000, '1er juillet 2022', 22.0, 'https://monnaies-euros.com/images/2euros_comme_PaysBas_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='portugal'), '35 ans du programme Erasmus', 750000, '1er juillet 2022', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Portugal2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='slovaquie'), '35 ans du programme Erasmus', 1000000, '1er juillet 2022', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name='35 ans du programme Erasmus'), (select id from countries where slug='slovenie'), '35 ans du programme Erasmus', 1000000, '1er juillet 2022', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Slovenie2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='allemagne'), 'Thuringe (série consacrée aux Länder)', 30000000, '25 janvier 2022', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='andorre'), 'La légende de Charlemagne', 70000, '4e trimestre 2022', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=1), (select id from countries where slug='andorre'), '10e anniversaire de l''entrée en vigueur de l''accord monétaire entre Andorre et l''Union européenne', 70000, '4e trimestre 2022', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='belgique'), 'Le secteur des soins de santé, en reconnaissance de son engagement exceptionnel pendant la pandémie de COVID-19', 2000000, 'Printemps 2022', 10.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='espagne'), '500e anniversaire de la circumnavigation de la terre', 1000000, '1er trimestre 2022', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=1), (select id from countries where slug='espagne'), 'UNESCO : parc national de Garajonay', 1000000, '1er trimestre 2022', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Espagne2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='estonie'), '150e anniversaire de la création de la Société des gens de lettres estoniens', 1000000, '1er trimestre 2022', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Estonie2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=1), (select id from countries where slug='estonie'), 'l''Ukraine et la liberté', 2000000, '4e trimestre 2022', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Estonie_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='finlande'), 'La recherche sur le climat en Finlande', 400000, 'automne 2022', 4.7, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=1), (select id from countries where slug='finlande'), '100 ans du ballet national finlandais', 400000, 'Printemps 2022', 4.7, 'https://monnaies-euros.com/images/2euros_comme_Finlande2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='france'), 'Jeux Olympiques de Paris 2024 - Génie', 260000, 'Septembre 2022', 16.0, 'https://monnaies-euros.com/images/2euros_comme_France2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=1), (select id from countries where slug='france'), '90e anniversaire de la naissance du président Jacques Chirac', 9000000, 'janvier 2022', 2.4, 'https://monnaies-euros.com/images/2euros_comme_France_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='grece'), '200e anniversaire de la première constitution grecque', 750000, 'Juillet 2022', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Grece_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='italie'), '30e anniversaire de la mort de Giovanni Falcone et Paolo Borsellino', 3000000, 'janvier 2022', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Italie2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=1), (select id from countries where slug='italie'), '170e anniversaire de la création de la police nationale italienne', 3000000, 'janvier 2022', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Italie_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='lettonie'), 'Le centenaire de la Banque de Lettonie – culture financière', 415000, 'avril/mai 2022', 3.9, 'https://monnaies-euros.com/images/2euros_comme_Lettonie_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='lituanie'), '100 ans du basketball en Lituanie', 750000, '2e trimestre 2022', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Lituanie2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=1), (select id from countries where slug='lituanie'), 'Suvalkija (série consacrée aux régions ethnographiques lituaniennes)', 500000, '4e trimestre 2022', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Lituanie_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='luxembourg'), '10e anniversaire de mariage du Grand-Duc héritier Guillaume et de la Grande-Duchesse héritière Stéphanie', 500000, 'avril 2022', 6.0, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=1), (select id from countries where slug='luxembourg'), '50e anniversaire de la protection juridique du drapeau luxembourgeois', 500000, 'janvier 2022', 6.0, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='malte'), '22e anniversaire de la résolution 1325 du Conseil de sécurité des Nations unies sur les femmes, la paix et la sécurité', 65500, 'Octobre 2022', 60.0, 'https://monnaies-euros.com/images/2euros_comme_Malte_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=1), (select id from countries where slug='malte'), 'UNESCO : L''hypogée de Ħal Saflieni', 192000, 'Mai 2022', 9.0, 'https://monnaies-euros.com/images/2euros_comme_Malte2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='monaco'), '100e anniversaire de la mort du prince Albert Ier', 15000, 'Septembre 2022', 375.0, 'https://monnaies-euros.com/images/2euros_comme_Monaco_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='portugal'), '100e anniversaire de la traversée aérienne de l''océan Atlantique Sud, réalisée en 1922 par Gago Coutinho et Sacadura Cabral', 1000000, 'Mars 2022', 2.8, 'https://monnaies-euros.com/images/2euros_comme2_Portugal_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='saint-marin'), '530e anniversaire de la mort de Piero della Francesca', 55000, 'Octobre 2022', 50.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=1), (select id from countries where slug='saint-marin'), 'Bicentenaire de la mort d''Antonio Canova', 55000, 'Octobre 2022', 50.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin2_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='slovaquie'), '300e anniversaire de la construction de la première machine à vapeur atmosphérique d''Europe continentale pour le drainage des mines', 1000000, 'Octobre 2022', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='slovenie'), '150e anniversaire de la naissance de l''architecte Jože Plečnik', 1000000, 'janvier 2022', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=0), (select id from countries where slug='vatican'), '25e anniversaire de la mort de Mère Teresa de Calcutta', 84000, 'Septembre 2022', 40.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2022.webp'),
  ((select id from commemorative_sets where year=2022 and name is null and sort_order=1), (select id from countries where slug='vatican'), '125e anniversaire de la naissance du pape Paul VI', 84000, 'Mars 2022', 34.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican2_2022.webp');
