-- ============================================================
-- Import des données réelles : sets Euro par pays
-- Source : https://monnaies-euros.com/euros.php (parsé directement, pas de reconstruction manuelle)
-- Flags non incluses (à sourcer séparément) : flag_url laissé vide
-- ============================================================

-- 1) Pays
insert into countries (name, slug, iso_code, flag_url, first_year, sort_order) values
  ('Allemagne', 'allemagne', 'DE', '', 2002, 0),
  ('Andorre', 'andorre', 'AD', '', 2014, 1),
  ('Autriche', 'autriche', 'AT', '', 2002, 2),
  ('Belgique', 'belgique', 'BE', '', 1999, 3),
  ('Bulgarie', 'bulgarie', 'BG', '', 2026, 4),
  ('Chypre', 'chypre', 'CY', '', 2008, 5),
  ('Croatie', 'croatie', 'HR', '', 2023, 6),
  ('Espagne', 'espagne', 'ES', '', 1999, 7),
  ('Estonie', 'estonie', 'EE', '', 2011, 8),
  ('Finlande', 'finlande', 'FI', '', 1999, 9),
  ('France', 'france', 'FR', '', 1999, 10),
  ('Grèce', 'grece', 'GR', '', 2002, 11),
  ('Irlande', 'irlande', 'IE', '', 2002, 12),
  ('Italie', 'italie', 'IT', '', 2002, 13),
  ('Lettonie', 'lettonie', 'LV', '', 2014, 14),
  ('Lituanie', 'lituanie', 'LT', '', 2015, 15),
  ('Luxembourg', 'luxembourg', 'LU', '', 2002, 16),
  ('Malte', 'malte', 'MT', '', 2008, 17),
  ('Monaco', 'monaco', 'MC', '', 2001, 18),
  ('Pays-Bas', 'pays-bas', 'NL', '', 1999, 19),
  ('Portugal', 'portugal', 'PT', '', 2002, 20),
  ('Saint-Marin', 'saint-marin', 'SM', '', 2002, 21),
  ('Slovaquie', 'slovaquie', 'SK', '', 2009, 22),
  ('Slovénie', 'slovenie', 'SI', '', 2007, 23),
  ('Vatican', 'vatican', 'VA', '', 2002, 24)
on conflict (slug) do nothing;

-- 2) Séries par pays
insert into coin_series (country_id, label, start_year, end_year, sort_order) values
  ((select id from countries where slug='allemagne'), '(2002-)', 2002, null, 0),
  ((select id from countries where slug='andorre'), '(2014-)', 2014, null, 0),
  ((select id from countries where slug='autriche'), '(2002-)', 2002, null, 0),
  ((select id from countries where slug='belgique'), '1re série (1999-2007)', 1999, 2007, 0),
  ((select id from countries where slug='belgique'), '2e série (2008)', 2008, 2008, 1),
  ((select id from countries where slug='belgique'), '3e série (2009-2013)', 2009, 2013, 2),
  ((select id from countries where slug='belgique'), '4e série (2014-)', 2014, null, 3),
  ((select id from countries where slug='bulgarie'), '(2026-)', 2026, null, 0),
  ((select id from countries where slug='chypre'), '(2008-)', 2008, null, 0),
  ((select id from countries where slug='croatie'), '(2023-)', 2023, null, 0),
  ((select id from countries where slug='espagne'), '1re série (1999-2009)', 1999, 2009, 0),
  ((select id from countries where slug='espagne'), '2e série (2010-2014)', 2010, 2014, 1),
  ((select id from countries where slug='espagne'), '3e série (2015-)', 2015, null, 2),
  ((select id from countries where slug='estonie'), '(2011-)', 2011, null, 0),
  ((select id from countries where slug='finlande'), '1re série (1999-2006)', 1999, 2006, 0),
  ((select id from countries where slug='finlande'), '2e série (2007-)', 2007, null, 1),
  ((select id from countries where slug='france'), '(1999-2021)', 1999, 2021, 0),
  ((select id from countries where slug='france'), '2e série (2022-2023)', 2022, 2023, 1),
  ((select id from countries where slug='france'), '2e série bis (2024-)', 2024, null, 2),
  ((select id from countries where slug='grece'), '(2002-)', 2002, null, 0),
  ((select id from countries where slug='irlande'), '(2002-)', 2002, null, 0),
  ((select id from countries where slug='italie'), '(2002-)', 2002, null, 0),
  ((select id from countries where slug='lettonie'), '(2014-)', 2014, null, 0),
  ((select id from countries where slug='lituanie'), '(2015-)', 2015, null, 0),
  ((select id from countries where slug='luxembourg'), '1re série (2002-2025)', 2002, 2025, 0),
  ((select id from countries where slug='luxembourg'), '2e série (2026-)', 2026, null, 1),
  ((select id from countries where slug='malte'), '(2008-)', 2008, null, 0),
  ((select id from countries where slug='monaco'), '1re série (2001-2005)', 2001, 2005, 0),
  ((select id from countries where slug='monaco'), '2e série (2006-2024)', 2006, 2024, 1),
  ((select id from countries where slug='monaco'), '3e série (2025-)', 2025, null, 2),
  ((select id from countries where slug='pays-bas'), '1re série (1999-2013)', 1999, 2013, 0),
  ((select id from countries where slug='pays-bas'), '2e série (2014-)', 2014, null, 1),
  ((select id from countries where slug='portugal'), '(2002-)', 2002, null, 0),
  ((select id from countries where slug='saint-marin'), '1re série (2002-2016)', 2002, 2016, 0),
  ((select id from countries where slug='saint-marin'), '2e série (2017-)', 2017, null, 1),
  ((select id from countries where slug='slovaquie'), '(2009-)', 2009, null, 0),
  ((select id from countries where slug='slovenie'), '(2007-)', 2007, null, 0),
  ((select id from countries where slug='vatican'), '1re série (2002-2005)', 2002, 2005, 0),
  ((select id from countries where slug='vatican'), '2e série (2005)', 2005, 2005, 1),
  ((select id from countries where slug='vatican'), '3e série (2006-2013)', 2006, 2013, 2),
  ((select id from countries where slug='vatican'), '4e série (2014-2016)', 2014, 2016, 3),
  ((select id from countries where slug='vatican'), '5e série (2017-2025)', 2017, 2025, 4),
  ((select id from countries where slug='vatican'), '6e série (2026-)', 2026, null, 5);

-- 3) Pièces (une ligne par série x valeur) — URLs copiées telles quelles depuis la source
insert into pieces (series_id, value, image_url) values
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='allemagne' and cs.label='(2002-)'), '1c', 'https://monnaies-euros.com/images/1centime_Allemagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='allemagne' and cs.label='(2002-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Allemagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='allemagne' and cs.label='(2002-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Allemagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='allemagne' and cs.label='(2002-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Allemagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='allemagne' and cs.label='(2002-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Allemagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='allemagne' and cs.label='(2002-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Allemagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='allemagne' and cs.label='(2002-)'), '1e', 'https://monnaies-euros.com/images/1euro_Allemagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='allemagne' and cs.label='(2002-)'), '2e', 'https://monnaies-euros.com/images/2euros_Allemagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='andorre' and cs.label='(2014-)'), '1c', 'https://monnaies-euros.com/images/1centime_Andorre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='andorre' and cs.label='(2014-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Andorre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='andorre' and cs.label='(2014-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Andorre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='andorre' and cs.label='(2014-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Andorre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='andorre' and cs.label='(2014-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Andorre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='andorre' and cs.label='(2014-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Andorre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='andorre' and cs.label='(2014-)'), '1e', 'https://monnaies-euros.com/images/1euro_Andorre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='andorre' and cs.label='(2014-)'), '2e', 'https://monnaies-euros.com/images/2euros_Andorre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='autriche' and cs.label='(2002-)'), '1c', 'https://monnaies-euros.com/images/1centime_Autriche_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='autriche' and cs.label='(2002-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Autriche_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='autriche' and cs.label='(2002-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Autriche_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='autriche' and cs.label='(2002-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Autriche_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='autriche' and cs.label='(2002-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Autriche_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='autriche' and cs.label='(2002-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Autriche_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='autriche' and cs.label='(2002-)'), '1e', 'https://monnaies-euros.com/images/1euro_Autriche_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='autriche' and cs.label='(2002-)'), '2e', 'https://monnaies-euros.com/images/2euros_Autriche_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='1re série (1999-2007)'), '1c', 'https://monnaies-euros.com/images/1centime_Belgique_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='1re série (1999-2007)'), '2c', 'https://monnaies-euros.com/images/2centimes_Belgique_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='1re série (1999-2007)'), '5c', 'https://monnaies-euros.com/images/5centimes_Belgique_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='1re série (1999-2007)'), '10c', 'https://monnaies-euros.com/images/10centimes_Belgique_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='1re série (1999-2007)'), '20c', 'https://monnaies-euros.com/images/20centimes_Belgique_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='1re série (1999-2007)'), '50c', 'https://monnaies-euros.com/images/50centimes_Belgique_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='1re série (1999-2007)'), '1e', 'https://monnaies-euros.com/images/1euro_Belgique_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='1re série (1999-2007)'), '2e', 'https://monnaies-euros.com/images/2euros_Belgique_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='2e série (2008)'), '1c', 'https://monnaies-euros.com/images/1centime_Belgique2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='2e série (2008)'), '2c', 'https://monnaies-euros.com/images/2centimes_Belgique2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='2e série (2008)'), '5c', 'https://monnaies-euros.com/images/5centimes_Belgique2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='2e série (2008)'), '10c', 'https://monnaies-euros.com/images/10centimes_Belgique2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='2e série (2008)'), '20c', 'https://monnaies-euros.com/images/20centimes_Belgique2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='2e série (2008)'), '50c', 'https://monnaies-euros.com/images/50centimes_Belgique2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='2e série (2008)'), '1e', 'https://monnaies-euros.com/images/1euro_Belgique2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='2e série (2008)'), '2e', 'https://monnaies-euros.com/images/2euros_Belgique2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='3e série (2009-2013)'), '1c', 'https://monnaies-euros.com/images/1centime_Belgique3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='3e série (2009-2013)'), '2c', 'https://monnaies-euros.com/images/2centimes_Belgique3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='3e série (2009-2013)'), '5c', 'https://monnaies-euros.com/images/5centimes_Belgique3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='3e série (2009-2013)'), '10c', 'https://monnaies-euros.com/images/10centimes_Belgique3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='3e série (2009-2013)'), '20c', 'https://monnaies-euros.com/images/20centimes_Belgique3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='3e série (2009-2013)'), '50c', 'https://monnaies-euros.com/images/50centimes_Belgique3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='3e série (2009-2013)'), '1e', 'https://monnaies-euros.com/images/1euro_Belgique3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='3e série (2009-2013)'), '2e', 'https://monnaies-euros.com/images/2euros_Belgique3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='4e série (2014-)'), '1c', 'https://monnaies-euros.com/images/1centime_Belgique4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='4e série (2014-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Belgique4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='4e série (2014-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Belgique4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='4e série (2014-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Belgique4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='4e série (2014-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Belgique4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='4e série (2014-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Belgique4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='4e série (2014-)'), '1e', 'https://monnaies-euros.com/images/1euro_Belgique4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='belgique' and cs.label='4e série (2014-)'), '2e', 'https://monnaies-euros.com/images/2euros_Belgique4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='bulgarie' and cs.label='(2026-)'), '1c', 'https://monnaies-euros.com/images/1centime_Bulgarie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='bulgarie' and cs.label='(2026-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Bulgarie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='bulgarie' and cs.label='(2026-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Bulgarie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='bulgarie' and cs.label='(2026-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Bulgarie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='bulgarie' and cs.label='(2026-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Bulgarie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='bulgarie' and cs.label='(2026-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Bulgarie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='bulgarie' and cs.label='(2026-)'), '1e', 'https://monnaies-euros.com/images/1euro_Bulgarie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='bulgarie' and cs.label='(2026-)'), '2e', 'https://monnaies-euros.com/images/2euros_Bulgarie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='chypre' and cs.label='(2008-)'), '1c', 'https://monnaies-euros.com/images/1centime_Chypre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='chypre' and cs.label='(2008-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Chypre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='chypre' and cs.label='(2008-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Chypre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='chypre' and cs.label='(2008-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Chypre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='chypre' and cs.label='(2008-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Chypre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='chypre' and cs.label='(2008-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Chypre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='chypre' and cs.label='(2008-)'), '1e', 'https://monnaies-euros.com/images/1euro_Chypre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='chypre' and cs.label='(2008-)'), '2e', 'https://monnaies-euros.com/images/2euros_Chypre_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='croatie' and cs.label='(2023-)'), '1c', 'https://monnaies-euros.com/images/1centime_Croatie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='croatie' and cs.label='(2023-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Croatie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='croatie' and cs.label='(2023-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Croatie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='croatie' and cs.label='(2023-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Croatie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='croatie' and cs.label='(2023-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Croatie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='croatie' and cs.label='(2023-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Croatie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='croatie' and cs.label='(2023-)'), '1e', 'https://monnaies-euros.com/images/1euro_Croatie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='croatie' and cs.label='(2023-)'), '2e', 'https://monnaies-euros.com/images/2euros_Croatie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='1re série (1999-2009)'), '1c', 'https://monnaies-euros.com/images/1centime_Espagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='1re série (1999-2009)'), '2c', 'https://monnaies-euros.com/images/2centimes_Espagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='1re série (1999-2009)'), '5c', 'https://monnaies-euros.com/images/5centimes_Espagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='1re série (1999-2009)'), '10c', 'https://monnaies-euros.com/images/10centimes_Espagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='1re série (1999-2009)'), '20c', 'https://monnaies-euros.com/images/20centimes_Espagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='1re série (1999-2009)'), '50c', 'https://monnaies-euros.com/images/50centimes_Espagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='1re série (1999-2009)'), '1e', 'https://monnaies-euros.com/images/1euro_Espagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='1re série (1999-2009)'), '2e', 'https://monnaies-euros.com/images/2euros_Espagne_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='2e série (2010-2014)'), '1c', 'https://monnaies-euros.com/images/1centime_Espagne2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='2e série (2010-2014)'), '2c', 'https://monnaies-euros.com/images/2centimes_Espagne2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='2e série (2010-2014)'), '5c', 'https://monnaies-euros.com/images/5centimes_Espagne2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='2e série (2010-2014)'), '10c', 'https://monnaies-euros.com/images/10centimes_Espagne2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='2e série (2010-2014)'), '20c', 'https://monnaies-euros.com/images/20centimes_Espagne2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='2e série (2010-2014)'), '50c', 'https://monnaies-euros.com/images/50centimes_Espagne2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='2e série (2010-2014)'), '1e', 'https://monnaies-euros.com/images/1euro_Espagne2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='2e série (2010-2014)'), '2e', 'https://monnaies-euros.com/images/2euros_Espagne2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='3e série (2015-)'), '1c', 'https://monnaies-euros.com/images/1centime_Espagne3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='3e série (2015-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Espagne3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='3e série (2015-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Espagne3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='3e série (2015-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Espagne3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='3e série (2015-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Espagne3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='3e série (2015-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Espagne3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='3e série (2015-)'), '1e', 'https://monnaies-euros.com/images/1euro_Espagne3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='espagne' and cs.label='3e série (2015-)'), '2e', 'https://monnaies-euros.com/images/2euros_Espagne3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='estonie' and cs.label='(2011-)'), '1c', 'https://monnaies-euros.com/images/1centime_Estonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='estonie' and cs.label='(2011-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Estonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='estonie' and cs.label='(2011-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Estonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='estonie' and cs.label='(2011-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Estonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='estonie' and cs.label='(2011-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Estonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='estonie' and cs.label='(2011-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Estonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='estonie' and cs.label='(2011-)'), '1e', 'https://monnaies-euros.com/images/1euro_Estonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='estonie' and cs.label='(2011-)'), '2e', 'https://monnaies-euros.com/images/2euros_Estonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='1re série (1999-2006)'), '1c', 'https://monnaies-euros.com/images/1centime_Finlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='1re série (1999-2006)'), '2c', 'https://monnaies-euros.com/images/2centimes_Finlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='1re série (1999-2006)'), '5c', 'https://monnaies-euros.com/images/5centimes_Finlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='1re série (1999-2006)'), '10c', 'https://monnaies-euros.com/images/10centimes_Finlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='1re série (1999-2006)'), '20c', 'https://monnaies-euros.com/images/20centimes_Finlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='1re série (1999-2006)'), '50c', 'https://monnaies-euros.com/images/50centimes_Finlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='1re série (1999-2006)'), '1e', 'https://monnaies-euros.com/images/1euro_Finlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='1re série (1999-2006)'), '2e', 'https://monnaies-euros.com/images/2euros_Finlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='2e série (2007-)'), '1c', 'https://monnaies-euros.com/images/1centime_Finlande2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='2e série (2007-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Finlande2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='2e série (2007-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Finlande2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='2e série (2007-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Finlande2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='2e série (2007-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Finlande2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='2e série (2007-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Finlande2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='2e série (2007-)'), '1e', 'https://monnaies-euros.com/images/1euro_Finlande2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='finlande' and cs.label='2e série (2007-)'), '2e', 'https://monnaies-euros.com/images/2euros_Finlande2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='(1999-2021)'), '1c', 'https://monnaies-euros.com/images/1centime_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='(1999-2021)'), '2c', 'https://monnaies-euros.com/images/2centimes_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='(1999-2021)'), '5c', 'https://monnaies-euros.com/images/5centimes_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='(1999-2021)'), '10c', 'https://monnaies-euros.com/images/10centimes_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='(1999-2021)'), '20c', 'https://monnaies-euros.com/images/20centimes_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='(1999-2021)'), '50c', 'https://monnaies-euros.com/images/50centimes_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='(1999-2021)'), '1e', 'https://monnaies-euros.com/images/1euro_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='(1999-2021)'), '2e', 'https://monnaies-euros.com/images/2euros_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série (2022-2023)'), '1c', 'https://monnaies-euros.com/images/1centime_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série (2022-2023)'), '2c', 'https://monnaies-euros.com/images/2centimes_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série (2022-2023)'), '5c', 'https://monnaies-euros.com/images/5centimes_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série (2022-2023)'), '10c', 'https://monnaies-euros.com/images/10centimes_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série (2022-2023)'), '20c', 'https://monnaies-euros.com/images/20centimes_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série (2022-2023)'), '50c', 'https://monnaies-euros.com/images/50centimes_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série (2022-2023)'), '1e', 'https://monnaies-euros.com/images/1euro_France2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série (2022-2023)'), '2e', 'https://monnaies-euros.com/images/2euros_France2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série bis (2024-)'), '1c', 'https://monnaies-euros.com/images/1centime_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série bis (2024-)'), '2c', 'https://monnaies-euros.com/images/2centimes_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série bis (2024-)'), '5c', 'https://monnaies-euros.com/images/5centimes_France_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série bis (2024-)'), '10c', 'https://monnaies-euros.com/images/10centimes_France2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série bis (2024-)'), '20c', 'https://monnaies-euros.com/images/20centimes_France2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série bis (2024-)'), '50c', 'https://monnaies-euros.com/images/50centimes_France2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série bis (2024-)'), '1e', 'https://monnaies-euros.com/images/1euro_France2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='france' and cs.label='2e série bis (2024-)'), '2e', 'https://monnaies-euros.com/images/2euros_France2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='grece' and cs.label='(2002-)'), '1c', 'https://monnaies-euros.com/images/1centime_Grece_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='grece' and cs.label='(2002-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Grece_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='grece' and cs.label='(2002-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Grece_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='grece' and cs.label='(2002-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Grece_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='grece' and cs.label='(2002-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Grece_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='grece' and cs.label='(2002-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Grece_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='grece' and cs.label='(2002-)'), '1e', 'https://monnaies-euros.com/images/1euro_Grece_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='grece' and cs.label='(2002-)'), '2e', 'https://monnaies-euros.com/images/2euros_Grece_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='irlande' and cs.label='(2002-)'), '1c', 'https://monnaies-euros.com/images/1centime_Irlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='irlande' and cs.label='(2002-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Irlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='irlande' and cs.label='(2002-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Irlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='irlande' and cs.label='(2002-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Irlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='irlande' and cs.label='(2002-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Irlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='irlande' and cs.label='(2002-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Irlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='irlande' and cs.label='(2002-)'), '1e', 'https://monnaies-euros.com/images/1euro_Irlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='irlande' and cs.label='(2002-)'), '2e', 'https://monnaies-euros.com/images/2euros_Irlande_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='italie' and cs.label='(2002-)'), '1c', 'https://monnaies-euros.com/images/1centime_Italie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='italie' and cs.label='(2002-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Italie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='italie' and cs.label='(2002-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Italie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='italie' and cs.label='(2002-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Italie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='italie' and cs.label='(2002-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Italie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='italie' and cs.label='(2002-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Italie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='italie' and cs.label='(2002-)'), '1e', 'https://monnaies-euros.com/images/1euro_Italie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='italie' and cs.label='(2002-)'), '2e', 'https://monnaies-euros.com/images/2euros_Italie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lettonie' and cs.label='(2014-)'), '1c', 'https://monnaies-euros.com/images/1centime_Lettonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lettonie' and cs.label='(2014-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Lettonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lettonie' and cs.label='(2014-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Lettonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lettonie' and cs.label='(2014-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Lettonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lettonie' and cs.label='(2014-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Lettonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lettonie' and cs.label='(2014-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Lettonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lettonie' and cs.label='(2014-)'), '1e', 'https://monnaies-euros.com/images/1euro_Lettonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lettonie' and cs.label='(2014-)'), '2e', 'https://monnaies-euros.com/images/2euros_Lettonie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lituanie' and cs.label='(2015-)'), '1c', 'https://monnaies-euros.com/images/1centime_Lituanie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lituanie' and cs.label='(2015-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Lituanie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lituanie' and cs.label='(2015-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Lituanie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lituanie' and cs.label='(2015-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Lituanie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lituanie' and cs.label='(2015-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Lituanie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lituanie' and cs.label='(2015-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Lituanie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lituanie' and cs.label='(2015-)'), '1e', 'https://monnaies-euros.com/images/1euro_Lituanie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='lituanie' and cs.label='(2015-)'), '2e', 'https://monnaies-euros.com/images/2euros_Lituanie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='1re série (2002-2025)'), '1c', 'https://monnaies-euros.com/images/1centime_Luxembourg_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='1re série (2002-2025)'), '2c', 'https://monnaies-euros.com/images/2centimes_Luxembourg_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='1re série (2002-2025)'), '5c', 'https://monnaies-euros.com/images/5centimes_Luxembourg_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='1re série (2002-2025)'), '10c', 'https://monnaies-euros.com/images/10centimes_Luxembourg_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='1re série (2002-2025)'), '20c', 'https://monnaies-euros.com/images/20centimes_Luxembourg_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='1re série (2002-2025)'), '50c', 'https://monnaies-euros.com/images/50centimes_Luxembourg_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='1re série (2002-2025)'), '1e', 'https://monnaies-euros.com/images/1euro_Luxembourg_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='1re série (2002-2025)'), '2e', 'https://monnaies-euros.com/images/2euros_Luxembourg_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='2e série (2026-)'), '1c', 'https://monnaies-euros.com/images/1centime_Luxembourg2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='2e série (2026-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Luxembourg2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='2e série (2026-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Luxembourg2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='2e série (2026-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Luxembourg2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='2e série (2026-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Luxembourg2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='2e série (2026-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Luxembourg2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='2e série (2026-)'), '1e', 'https://monnaies-euros.com/images/1euro_Luxembourg_Euro2.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='luxembourg' and cs.label='2e série (2026-)'), '2e', 'https://monnaies-euros.com/images/2euros_Luxembourg_Euro2.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='malte' and cs.label='(2008-)'), '1c', 'https://monnaies-euros.com/images/1centime_Malte_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='malte' and cs.label='(2008-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Malte_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='malte' and cs.label='(2008-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Malte_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='malte' and cs.label='(2008-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Malte_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='malte' and cs.label='(2008-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Malte_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='malte' and cs.label='(2008-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Malte_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='malte' and cs.label='(2008-)'), '1e', 'https://monnaies-euros.com/images/1euro_Malte_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='malte' and cs.label='(2008-)'), '2e', 'https://monnaies-euros.com/images/2euros_Malte_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='1re série (2001-2005)'), '1c', 'https://monnaies-euros.com/images/1centime_Monaco_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='1re série (2001-2005)'), '2c', 'https://monnaies-euros.com/images/2centimes_Monaco_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='1re série (2001-2005)'), '5c', 'https://monnaies-euros.com/images/5centimes_Monaco_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='1re série (2001-2005)'), '10c', 'https://monnaies-euros.com/images/10centimes_Monaco_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='1re série (2001-2005)'), '20c', 'https://monnaies-euros.com/images/20centimes_Monaco_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='1re série (2001-2005)'), '50c', 'https://monnaies-euros.com/images/50centimes_Monaco_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='1re série (2001-2005)'), '1e', 'https://monnaies-euros.com/images/1euro_Monaco_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='1re série (2001-2005)'), '2e', 'https://monnaies-euros.com/images/2euros_Monaco_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='2e série (2006-2024)'), '1c', 'https://monnaies-euros.com/images/1centime_Monaco2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='2e série (2006-2024)'), '2c', 'https://monnaies-euros.com/images/2centimes_Monaco2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='2e série (2006-2024)'), '5c', 'https://monnaies-euros.com/images/5centimes_Monaco2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='2e série (2006-2024)'), '10c', 'https://monnaies-euros.com/images/10centimes_Monaco2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='2e série (2006-2024)'), '20c', 'https://monnaies-euros.com/images/20centimes_Monaco2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='2e série (2006-2024)'), '50c', 'https://monnaies-euros.com/images/50centimes_Monaco2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='2e série (2006-2024)'), '1e', 'https://monnaies-euros.com/images/1euro_Monaco2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='2e série (2006-2024)'), '2e', 'https://monnaies-euros.com/images/2euros_Monaco2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='3e série (2025-)'), '1c', 'https://monnaies-euros.com/images/1centime_Monaco3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='3e série (2025-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Monaco3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='3e série (2025-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Monaco3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='3e série (2025-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Monaco3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='3e série (2025-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Monaco3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='3e série (2025-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Monaco3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='3e série (2025-)'), '1e', 'https://monnaies-euros.com/images/1euro_Monaco3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='monaco' and cs.label='3e série (2025-)'), '2e', 'https://monnaies-euros.com/images/2euros_Monaco3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='1re série (1999-2013)'), '1c', 'https://monnaies-euros.com/images/1centime_PaysBas_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='1re série (1999-2013)'), '2c', 'https://monnaies-euros.com/images/2centimes_PaysBas_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='1re série (1999-2013)'), '5c', 'https://monnaies-euros.com/images/5centimes_PaysBas_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='1re série (1999-2013)'), '10c', 'https://monnaies-euros.com/images/10centimes_PaysBas_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='1re série (1999-2013)'), '20c', 'https://monnaies-euros.com/images/20centimes_PaysBas_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='1re série (1999-2013)'), '50c', 'https://monnaies-euros.com/images/50centimes_PaysBas_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='1re série (1999-2013)'), '1e', 'https://monnaies-euros.com/images/1euro_PaysBas_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='1re série (1999-2013)'), '2e', 'https://monnaies-euros.com/images/2euros_PaysBas_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='2e série (2014-)'), '1c', 'https://monnaies-euros.com/images/1centime_PaysBas2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='2e série (2014-)'), '2c', 'https://monnaies-euros.com/images/2centimes_PaysBas2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='2e série (2014-)'), '5c', 'https://monnaies-euros.com/images/5centimes_PaysBas2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='2e série (2014-)'), '10c', 'https://monnaies-euros.com/images/10centimes_PaysBas2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='2e série (2014-)'), '20c', 'https://monnaies-euros.com/images/20centimes_PaysBas2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='2e série (2014-)'), '50c', 'https://monnaies-euros.com/images/50centimes_PaysBas2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='2e série (2014-)'), '1e', 'https://monnaies-euros.com/images/1euro_PaysBas2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='pays-bas' and cs.label='2e série (2014-)'), '2e', 'https://monnaies-euros.com/images/2euros_PaysBas2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='portugal' and cs.label='(2002-)'), '1c', 'https://monnaies-euros.com/images/1centime_Portugal_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='portugal' and cs.label='(2002-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Portugal_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='portugal' and cs.label='(2002-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Portugal_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='portugal' and cs.label='(2002-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Portugal_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='portugal' and cs.label='(2002-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Portugal_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='portugal' and cs.label='(2002-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Portugal_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='portugal' and cs.label='(2002-)'), '1e', 'https://monnaies-euros.com/images/1euro_Portugal_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='portugal' and cs.label='(2002-)'), '2e', 'https://monnaies-euros.com/images/2euros_Portugal_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='1re série (2002-2016)'), '1c', 'https://monnaies-euros.com/images/1centime_SaintMarin_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='1re série (2002-2016)'), '2c', 'https://monnaies-euros.com/images/2centimes_SaintMarin_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='1re série (2002-2016)'), '5c', 'https://monnaies-euros.com/images/5centimes_SaintMarin_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='1re série (2002-2016)'), '10c', 'https://monnaies-euros.com/images/10centimes_SaintMarin_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='1re série (2002-2016)'), '20c', 'https://monnaies-euros.com/images/20centimes_SaintMarin_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='1re série (2002-2016)'), '50c', 'https://monnaies-euros.com/images/50centimes_SaintMarin_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='1re série (2002-2016)'), '1e', 'https://monnaies-euros.com/images/1euro_SaintMarin_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='1re série (2002-2016)'), '2e', 'https://monnaies-euros.com/images/2euros_SaintMarin_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='2e série (2017-)'), '1c', 'https://monnaies-euros.com/images/1centime_SaintMarin2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='2e série (2017-)'), '2c', 'https://monnaies-euros.com/images/2centimes_SaintMarin2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='2e série (2017-)'), '5c', 'https://monnaies-euros.com/images/5centimes_SaintMarin2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='2e série (2017-)'), '10c', 'https://monnaies-euros.com/images/10centimes_SaintMarin2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='2e série (2017-)'), '20c', 'https://monnaies-euros.com/images/20centimes_SaintMarin2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='2e série (2017-)'), '50c', 'https://monnaies-euros.com/images/50centimes_SaintMarin2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='2e série (2017-)'), '1e', 'https://monnaies-euros.com/images/1euro_SaintMarin2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='saint-marin' and cs.label='2e série (2017-)'), '2e', 'https://monnaies-euros.com/images/2euros_SaintMarin2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovaquie' and cs.label='(2009-)'), '1c', 'https://monnaies-euros.com/images/1centime_Slovaquie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovaquie' and cs.label='(2009-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Slovaquie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovaquie' and cs.label='(2009-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Slovaquie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovaquie' and cs.label='(2009-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Slovaquie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovaquie' and cs.label='(2009-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Slovaquie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovaquie' and cs.label='(2009-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Slovaquie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovaquie' and cs.label='(2009-)'), '1e', 'https://monnaies-euros.com/images/1euro_Slovaquie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovaquie' and cs.label='(2009-)'), '2e', 'https://monnaies-euros.com/images/2euros_Slovaquie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovenie' and cs.label='(2007-)'), '1c', 'https://monnaies-euros.com/images/1centime_Slovenie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovenie' and cs.label='(2007-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Slovenie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovenie' and cs.label='(2007-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Slovenie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovenie' and cs.label='(2007-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Slovenie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovenie' and cs.label='(2007-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Slovenie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovenie' and cs.label='(2007-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Slovenie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovenie' and cs.label='(2007-)'), '1e', 'https://monnaies-euros.com/images/1euro_Slovenie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='slovenie' and cs.label='(2007-)'), '2e', 'https://monnaies-euros.com/images/2euros_Slovenie_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='1re série (2002-2005)'), '1c', 'https://monnaies-euros.com/images/1centime_Vatican_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='1re série (2002-2005)'), '2c', 'https://monnaies-euros.com/images/2centimes_Vatican_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='1re série (2002-2005)'), '5c', 'https://monnaies-euros.com/images/5centimes_Vatican_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='1re série (2002-2005)'), '10c', 'https://monnaies-euros.com/images/10centimes_Vatican_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='1re série (2002-2005)'), '20c', 'https://monnaies-euros.com/images/20centimes_Vatican_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='1re série (2002-2005)'), '50c', 'https://monnaies-euros.com/images/50centimes_Vatican_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='1re série (2002-2005)'), '1e', 'https://monnaies-euros.com/images/1euro_Vatican_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='1re série (2002-2005)'), '2e', 'https://monnaies-euros.com/images/2euros_Vatican_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='2e série (2005)'), '1c', 'https://monnaies-euros.com/images/1centime_Vatican2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='2e série (2005)'), '2c', 'https://monnaies-euros.com/images/2centimes_Vatican2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='2e série (2005)'), '5c', 'https://monnaies-euros.com/images/5centimes_Vatican2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='2e série (2005)'), '10c', 'https://monnaies-euros.com/images/10centimes_Vatican2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='2e série (2005)'), '20c', 'https://monnaies-euros.com/images/20centimes_Vatican2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='2e série (2005)'), '50c', 'https://monnaies-euros.com/images/50centimes_Vatican2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='2e série (2005)'), '1e', 'https://monnaies-euros.com/images/1euro_Vatican2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='2e série (2005)'), '2e', 'https://monnaies-euros.com/images/2euros_Vatican2_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='3e série (2006-2013)'), '1c', 'https://monnaies-euros.com/images/1centime_Vatican3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='3e série (2006-2013)'), '2c', 'https://monnaies-euros.com/images/2centimes_Vatican3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='3e série (2006-2013)'), '5c', 'https://monnaies-euros.com/images/5centimes_Vatican3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='3e série (2006-2013)'), '10c', 'https://monnaies-euros.com/images/10centimes_Vatican3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='3e série (2006-2013)'), '20c', 'https://monnaies-euros.com/images/20centimes_Vatican3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='3e série (2006-2013)'), '50c', 'https://monnaies-euros.com/images/50centimes_Vatican3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='3e série (2006-2013)'), '1e', 'https://monnaies-euros.com/images/1euro_Vatican3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='3e série (2006-2013)'), '2e', 'https://monnaies-euros.com/images/2euros_Vatican3_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='4e série (2014-2016)'), '1c', 'https://monnaies-euros.com/images/1centime_Vatican4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='4e série (2014-2016)'), '2c', 'https://monnaies-euros.com/images/2centimes_Vatican4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='4e série (2014-2016)'), '5c', 'https://monnaies-euros.com/images/5centimes_Vatican4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='4e série (2014-2016)'), '10c', 'https://monnaies-euros.com/images/10centimes_Vatican4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='4e série (2014-2016)'), '20c', 'https://monnaies-euros.com/images/20centimes_Vatican4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='4e série (2014-2016)'), '50c', 'https://monnaies-euros.com/images/50centimes_Vatican4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='4e série (2014-2016)'), '1e', 'https://monnaies-euros.com/images/1euro_Vatican4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='4e série (2014-2016)'), '2e', 'https://monnaies-euros.com/images/2euros_Vatican4_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='5e série (2017-2025)'), '1c', 'https://monnaies-euros.com/images/1centime_Vatican5_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='5e série (2017-2025)'), '2c', 'https://monnaies-euros.com/images/2centimes_Vatican5_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='5e série (2017-2025)'), '5c', 'https://monnaies-euros.com/images/5centimes_Vatican5_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='5e série (2017-2025)'), '10c', 'https://monnaies-euros.com/images/10centimes_Vatican5_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='5e série (2017-2025)'), '20c', 'https://monnaies-euros.com/images/20centimes_Vatican5_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='5e série (2017-2025)'), '50c', 'https://monnaies-euros.com/images/50centimes_Vatican5_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='5e série (2017-2025)'), '1e', 'https://monnaies-euros.com/images/1euro_Vatican5_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='5e série (2017-2025)'), '2e', 'https://monnaies-euros.com/images/2euros_Vatican5_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='6e série (2026-)'), '1c', 'https://monnaies-euros.com/images/1centime_Vatican6_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='6e série (2026-)'), '2c', 'https://monnaies-euros.com/images/2centimes_Vatican6_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='6e série (2026-)'), '5c', 'https://monnaies-euros.com/images/5centimes_Vatican6_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='6e série (2026-)'), '10c', 'https://monnaies-euros.com/images/10centimes_Vatican6_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='6e série (2026-)'), '20c', 'https://monnaies-euros.com/images/20centimes_Vatican6_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='6e série (2026-)'), '50c', 'https://monnaies-euros.com/images/50centimes_Vatican6_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='6e série (2026-)'), '1e', 'https://monnaies-euros.com/images/1euro_Vatican6_Euro.webp'),
  ((select cs.id from coin_series cs join countries c on c.id=cs.country_id where c.slug='vatican' and cs.label='6e série (2026-)'), '2e', 'https://monnaies-euros.com/images/2euros_Vatican6_Euro.webp')
on conflict (series_id, value) do update set image_url = excluded.image_url;
