-- ============================================================
-- Import des 2€ commémoratives 2024 (35 pièces)
-- Aucune édition de la liste blanche cette année-là -> tout sur
-- des lignes génériques (jusqu'à 2 par pays -> 2 lignes).
-- Nécessite fix_and_import_2011_2017.sql déjà exécuté.
-- ============================================================

insert into commemorative_sets (year, name, sort_order) values
  (2024, null, 0),
  (2024, null, 1);

insert into commemorative_coins (set_id, country_id, name, mintage, issue_date, quotation, image_url) values
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='allemagne'), 'Mecklembourg-Poméranie-Occidentale', 30000000, 'janvier 2024', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='allemagne'), '175e anniversaire de la Constitution de Francfort', 30000000, 'mars 2024', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='andorre'), '100 ans de ski en Andorre', 60000, 'dernier trimestre 2024', 22.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='andorre'), 'Championnats du monde de VTT UCI 2024', 60000, 'dernier trimestre 2024', 22.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='belgique'), 'lutte contre le cancer en Belgique', 2130000, 'mai 2024', 8.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='belgique'), 'Présidence belge du Conseil de l''UE', 2128500, '1er trimestre 2024', 8.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='chypre'), '20 ans d''adhésion de Chypre à l''Union européenne', 7000, '4e trimestre 2024', 1100.0, 'https://monnaies-euros.com/images/2euros_comme_Chypre_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='croatie'), '500e anniversaire de la mort de Marko Marulić', 200000, 'octobre 2024', 12.0, 'https://monnaies-euros.com/images/2euros_comme_Croatie2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='croatie'), 'Varaždin (Stari grad Varaždin – la vieille ville de Varaždin)', 200000, 'juin 2024', 12.0, 'https://monnaies-euros.com/images/2euros_comme_Croatie_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='espagne'), 'Inscription de Séville (Archives des Indes, Alcazar et cathédrale) au patrimoine mondial de l''UNESCO', 1500000, '1er trimestre 2024', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='espagne'), 'Bicentenaire de la création de la police nationale en tant que force de sécurité de l''État', 1500000, '1er trimestre 2024', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Espagne2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='estonie'), 'un bleuet, fleur nationale de l''Estonie', 1000000, '2e trimestre 2024', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Estonie_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='finlande'), 'Architecture finlandaise', 400000, 'automne 2024', 4.5, 'https://monnaies-euros.com/images/2euros_comme_Finlande2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='finlande'), 'Elections et démocratie', 400000, 'printemps 2024', 4.5, 'https://monnaies-euros.com/images/2euros_comme_Finalnde_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='france'), 'Jeux Olympiques de Paris 2024 - Hercule', 510000, 'janvier 2024', 13.0, 'https://monnaies-euros.com/images/2euros_comme_France_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='france'), 'Tour Eiffel', 24000000, 'mai 2024', 2.2, 'https://monnaies-euros.com/images/2euros_comme_France2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='grece'), '150e anniversaire de la naissance de Pénélope Delta', 750000, 'juillet 2024', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Grece_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='grece'), '50e anniversaire du rétablissement de la démocratie en Grèce', 750000, 'juillet 2024', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Grece2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='italie'), 'Rita Levi-Montalcini', 3000000, 'janvier 2024', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Italie2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='italie'), '250e anniversaire de la fondation de la Garde des finances', 3000000, 'janvier 2024', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Italie_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='lettonie'), 'l''himmeli', 415000, 'octobre/novembre 2024', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Lettonie_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='lituanie'), 'Tradition lituanienne des jardins de paille (sodai), inscrite sur la liste représentative du patrimoine culturel immatériel de l''humanité de l''Unesco', 500000, '4e trimestre 2024', 3.3, 'https://monnaies-euros.com/images/2euros_comme_Lituanie_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='luxembourg'), '175e anniversaire de la mort du Grand-Duc Guillaume II', 200000, 'janvier 2024', 10.0, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='luxembourg'), 'Feierstéppler', 200000, 'janvier 2024', 10.0, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='malte'), 'L''abeille de Malte', 85500, 'juin 2024', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Malte2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='malte'), 'Iċ-Ċittadella (la citadelle)', 85500, 'juin 2024', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Malte_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='monaco'), '500e anniversaire de la signature du traité avec Charles Quint', 15000, 'juin 2024', 300.0, 'https://monnaies-euros.com/images/2euros_comme_Monaco_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='portugal'), 'participation du Portugal aux 33e Jeux olympiques', 520000, 'juillet 2024', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Portugal2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='portugal'), '50e anniversaire du 25 avril 1974', 515000, 'avril 2024', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Portugal_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='saint-marin'), '530e anniversaire de la mort de Ghirlandaio', 56000, 'septembre 2024', 36.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='saint-marin'), '50e anniversaire de la déclaration des droits des citoyens et des principes fondamentaux de l''ordre juridique de Saint-Marin', 56000, 'avril 2024', 36.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='slovaquie'), '100e anniversaire du marathon de la paix de Košice', 1000000, 'septembre 2024', 2.7, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='slovenie'), '250 ans de la bibliothèque nationale et universitaire de Slovénie (Narodna in univerzitetna knjižnica)', 1000000, 'novembre 2024', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=0), (select id from countries where slug='vatican'), '750e anniversaire de la mort de Saint Thomas d''Aquin', 82900, 'octobre 2024', 32.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican2_2024.webp'),
  ((select id from commemorative_sets where year=2024 and name is null and sort_order=1), (select id from countries where slug='vatican'), '150e anniversaire de la naissance de Guglielmo Marconi', 82900, 'mai 2024', 85.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2024.webp');
