-- ============================================================
-- Import des 2€ commémoratives 2018 (36 pièces)
-- Aucune édition de la liste blanche cette année-là -> tout sur
-- des lignes génériques (jusqu'à 2 par pays -> 2 lignes).
-- Note : Estonie/Lettonie/Lituanie partagent un nom (100 ans des
-- états baltes) par coïncidence, mais hors liste blanche -> chacune
-- reste sur sa propre ligne générique.
-- Nécessite fix_and_import_2011_2017.sql déjà exécuté (retire la
-- contrainte 1-set-générique-par-année).
-- ============================================================

insert into commemorative_sets (year, name, sort_order) values
  (2018, null, 0),
  (2018, null, 1);

insert into commemorative_coins (set_id, country_id, name, mintage, issue_date, quotation, image_url) values
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='allemagne'), 'Berlin', 30000000, 'janvier 2018', 2.2, 'https://monnaies-euros.com/images/2euros_comme2_Allemagne_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='allemagne'), '100e anniversaire de la naissance du grand homme d''État et chancelier allemand Helmut Schmidt (1918-2015)', 30000000, 'janvier 2018', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='andorre'), '70e anniversaire de la Déclaration universelle des droits de l''Homme', 75000, 'novembre 2018', 19.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='andorre'), '25e anniversaire de la Constitution de la Principauté d''Andorre', 75000, 'janvier 2018', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='autriche'), '100e anniversaire de la République autrichienne', 18100100, 'décembre 2017', 2.3, 'https://monnaies-euros.com/images/2euros_comme_Autriche_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='belgique'), '50e anniversaire du satellite ESRO 2B', 260000, 'octobre 2018', 10.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='belgique'), '50e anniversaire des événements de mai 1968 en Belgique', 260000, 'mai/juin 2018', 10.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='espagne'), '50e anniversaire du Roi FELIPE VI', 400000, 'février 2018', 7.0, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='espagne'), 'Saint-Jacques-de-Compostelle', 300000, 'février 2018', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Espagne2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='estonie'), 'Célébration des 100 ans de la création de l''État estonien et de l''État letton ainsi que la restauration de l''État lituanien', 500000, 'janvier 2018', 6.0, 'https://monnaies-euros.com/images/2euros_comme_Estonie_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='estonie'), 'Centenaire de l''indépendance de l''Estonie', 1000000, 'janvier 2018', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Estonie2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='finlande'), 'Culture du sauna finlandais', 1000000, 'octobre 2018', 3.4, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='finlande'), 'Paysage du parc national de Koli en Finlande', 1000000, 'avril 2018', 3.4, 'https://monnaies-euros.com/images/2euros_comme_Finlande2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='france'), 'Simone Veil', 15000000, 'mai/juin 2018', 2.2, 'https://monnaies-euros.com/images/2euros_comme_France_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='france'), 'Bleuet du souvenir (Bleuet de France)', 15000000, 'janvier 2018', 2.2, 'https://monnaies-euros.com/images/2euros_comme_France2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='grece'), '75e anniversaire de la mort de Kostis Palamas', 750000, 'octobre 2018', 3.7, 'https://monnaies-euros.com/images/2euros_comme_Grece_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='grece'), '70e anniversaire du rattachement du Dodécanèse à la Grèce', 750000, 'octobre 2018', 3.7, 'https://monnaies-euros.com/images/2euros_comme_Grece2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='italie'), '70e anniversaire de l''entrée en vigueur de la Constitution italienne', 4000000, 'janvier 2018', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Italie2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='italie'), '60e anniversaire de la création du ministère italien de la Santé', 3000000, 'mars 2018', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Italie_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='lettonie'), 'Zemgale', 512000, 'septembre 2018', 3.9, 'https://monnaies-euros.com/images/2euros_comme_Lettonie_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='lettonie'), 'Célébration des 100 ans de la création de l''État estonien et de l''État letton ainsi que la restauration de l''État lituanien', 512000, 'janvier 2018', 3.9, 'https://monnaies-euros.com/images/2euros_comme_Lettonie2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='lituanie'), 'les célébrations de chants et danses lituaniennes', 500000, 'avril 2018', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Lituanie_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='lituanie'), 'Célébration des 100 ans de la création de l''État estonien et de l''État letton ainsi que la restauration de l''État lituanien', 1000000, 'janvier 2018', 3.6, 'https://monnaies-euros.com/images/2euros_comme_Lituanie2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='luxembourg'), '175e anniversaire de la mort du Grand-Duc Guillaume Ier', 500000, 'septembre 2018', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='luxembourg'), '150e anniversaire de la Constitution luxembourgeoise', 500000, 'janvier 2018', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='malte'), 'Patrimoine culturel', 320000, 'novembre 2018', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Malte_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='malte'), 'Temples de Mnajdra', 320000, 'juillet 2018', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Malte2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='monaco'), 'François-Joseph Bosio', 16000, 'juin 2018', 500.0, 'https://monnaies-euros.com/images/2euros_comme_Monaco_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='portugal'), '250 ans du jardin botanique d''Ajuda (Jardim Botânico da Ajuda)', 520000, 'juillet 2018', 3.6, 'https://monnaies-euros.com/images/2euros_comme_Portugal_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='portugal'), '250e anniversaire de l''Imprimerie nationale (« Imprensa Nacional »)', 520000, 'mai 2018', 3.6, 'https://monnaies-euros.com/images/2euros_comme_Portugal2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='saint-marin'), '420e anniversaire de la naissance de Gian Lorenzo Bernini', 60500, 'septembre 2018', 50.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='saint-marin'), '500e anniversaire de la naissance du Tintoret', 60500, 'avril 2018', 50.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin2_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='slovaquie'), '25e anniversaire de la création de la République slovaque', 1000000, 'janvier 2018', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='slovenie'), 'Journée mondiale des abeilles à l''initiative de la Slovénie', 1000000, 'avril 2018', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=0), (select id from countries where slug='vatican'), '50e anniversaire de la mort du Padre Pio', 101000, 'octobre 2018', 40.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2018.webp'),
  ((select id from commemorative_sets where year=2018 and name is null and sort_order=1), (select id from countries where slug='vatican'), 'Groupe de Laocoon - année européenne du patrimoine culturel', 101000, 'mai 2018', 35.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican2_2018.webp');
