-- ============================================================
-- Import des 2€ commémoratives 2016 (32 pièces)
-- Aucune édition de la liste blanche cette année-là -> tout sur
-- la ligne générique 2016.
-- À exécuter après reset_commemoratives.sql + import 2011-2015.
-- ============================================================

insert into commemorative_sets (year, name, sort_order) values
  (2016, null, 0)
on conflict (year) where name is null do nothing;

insert into commemorative_coins (set_id, country_id, name, mintage, issue_date, quotation, image_url) values
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='allemagne'), 'Saxe (série des länder)', 30000000, 'février 2016', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='andorre'), '25e anniversaire de la radio et de la télévision d''Andorre', 85000, 'décembre 2016', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='andorre'), '150e anniversaire de la «Nouvelle Réforme» de 1866', 85000, 'décembre 2016', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre2_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='autriche'), '200 ans de la Banque nationale d''Autriche (Oesterreichische Nationalbank)', 16000000, 'janvier 2016', 2.3, 'https://monnaies-euros.com/images/2euros_comme_Autriche_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='belgique'), 'Jeux olympiques', 375000, 'mars 2016', 10.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique2_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='belgique'), 'Journée internationale des enfants disparus', 1020000, 'mai 2016', 5.5, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='espagne'), 'Sites culturels et naturels du patrimoine mondial de l''Unesco – Segovia', 8000000, 'février 2016', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='estonie'), '100e anniversaire de la naissance de Paul Keres, célèbre grand-maître estonien du jeu d''échecs', 500000, 'janvier 2016', 6.0, 'https://monnaies-euros.com/images/2euros_comme_Estonie_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='finlande'), 'Eino Leino, écrivain et poète finlandais', 1000000, 'avril 2016', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Finlande2_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='finlande'), '100e anniversaire de la naissance du philosophe Georg Henrik von Wright', 1000000, 'octobre 2016', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='france'), 'François Mitterrand', 10000000, 'octobre 2016', 2.3, 'https://monnaies-euros.com/images/2euros_comme_France_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='france'), 'Championnat d''Europe de l''UEFA 2016', 10000000, 'janvier 2016', 2.3, 'https://monnaies-euros.com/images/2euros_comme_France2_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='grece'), '150e anniversaire de l''incendie du monastère d''Arkadi', 750000, 'décembre 2016', 3.9, 'https://monnaies-euros.com/images/2euros_comme_Grece_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='grece'), '120e anniversaire de la naissance de Dimitri Mitropoulos', 750000, 'décembre 2016', 3.9, 'https://monnaies-euros.com/images/2euros_comme_Grece2_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='irlande'), 'Centenaire du soulèvement de Pâques 1916 en Irlande', 4500000, 'janvier 2016', 2.7, 'https://monnaies-euros.com/images/2euros_comme_Irlande_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='italie'), '550e anniversaire de la mort de Donatello', 1500000, 'mars 2016', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Italie_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='italie'), '2 200e anniversaire de la mort de Titus Maccius Plautus', 1500000, 'mars 2016', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Italie2_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='lettonie'), 'Agriculture lettone', 1010000, 'juin 2016', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Lettonie2_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='lettonie'), 'Vidzeme', 1030000, 'novembre 2016', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Lettonie_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='lituanie'), 'La culture balte', 1000000, 'mai 2016', 3.7, 'https://monnaies-euros.com/images/2euros_comme_Lituanie_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='luxembourg'), '50e anniversaire du pont « Grande-Duchesse Charlotte »', 1000000, '1er trimestre 2016', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='malte'), 'le rôle de la Malta Community Chest Fund dans la société', 380000, 'novembre 2016', 4.5, 'https://monnaies-euros.com/images/2euros_comme_Malte_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='malte'), 'Temples de Ġgantija', 350000, 'juillet 2016', 4.5, 'https://monnaies-euros.com/images/2euros_comme_Malte2_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='monaco'), '150e anniversaire de la fondation de Monte-Carlo par Charles III', 15000, 'juin 2016', 1200.0, 'https://monnaies-euros.com/images/2euros_comme_Monaco_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='portugal'), '50e anniversaire du premier pont réunissant les deux rives du Tage', 500000, 'juillet 2016', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Portugal_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='portugal'), 'Equipe portugaise participant aux Jeux olympiques de Rio en 2016', 650000, 'mars 2016', 3.8, 'https://monnaies-euros.com/images/2euros_comme_Portugal2_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='saint-marin'), '400e anniversaire de la mort de William Shakespeare', 85000, 'septembre 2016', 35.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='saint-marin'), '550e anniversaire de la mort de Donatello', 85000, 'avril 2016', 35.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin2_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='slovaquie'), 'Première présidence slovaque du Conseil de l''Union européenne', 1000000, 'mars 2016', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='slovenie'), '25e anniversaire de l''indépendance de la République de Slovénie', 1000000, 'juin 2016', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='vatican'), 'Jubilé de la Miséricorde', 105000, 'octobre 2016', 45.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2016.webp'),
  ((select id from commemorative_sets where year=2016 and name is null), (select id from countries where slug='vatican'), '200e anniversaire du Corps de gendarmerie de l''État de la Cité du Vatican', 105000, 'juin 2016', 45.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican2_2016.webp')
on conflict (set_id, country_id) do nothing;
