-- ============================================================
-- Import des 2€ commémoratives 2023 (36 pièces)
-- Aucune édition de la liste blanche cette année-là -> tout sur
-- des lignes génériques (jusqu'à 2 par pays -> 2 lignes).
-- La Croatie apparaît pour la première fois (entrée en zone euro
-- le 1er janvier 2023) — le pays existe déjà en base (import_sets.sql).
-- Nécessite fix_and_import_2011_2017.sql déjà exécuté.
-- ============================================================

insert into commemorative_sets (year, name, sort_order) values
  (2023, null, 0),
  (2023, null, 1);

insert into commemorative_coins (set_id, country_id, name, mintage, issue_date, quotation, image_url) values
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='allemagne'), 'Hambourg (série consacrée aux Länder)', 30000000, 'janvier 2023', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='allemagne'), '1 275e anniversaire de la naissance de Charlemagne (748-814), roi des Francs et empereur du Saint-Empire romain', 20000000, 'Mars 2023', 2.3, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='andorre'), '30e anniversaire de l''adhésion de la Principauté d''Andorre aux Nations unies', 70000, 'dernier trimestre 2023', 24.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='andorre'), 'Fêtes du feu du solstice d''été dans les Pyrénées', 70000, 'dernier trimestre 2023', 24.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='belgique'), '75e anniversaire du droit de vote des femmes en Belgique', 130000, 'octobre 2023', 13.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='belgique'), 'l''« année de l''Art nouveau », célébrée par la Belgique en 2023', 155000, 'Juin 2023', 10.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='chypre'), '60e anniversaire de la création de la Banque centrale de Chypre', 412000, 'mi 2023', 5.0, 'https://monnaies-euros.com/images/2euros_comme_Chypre_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='croatie'), 'Introduction de l''euro comme monnaie officielle de la Croatie le 1er janvier 2023', 250000, 'Septembre 2023', 11.0, 'https://monnaies-euros.com/images/2euros_comme_Croatie_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='espagne'), 'UNESCO : Cáceres', 1500000, '1er trimestre 2023', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Espagne2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='espagne'), 'Présidence espagnole du Conseil de l''Union européenne', 1500000, '1er juin 2023', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='estonie'), 'Oiseau national de l''Estonie – l''hirondelle rustique', 1000000, '2e trimestre 2023', 3.5, 'https://monnaies-euros.com/images/2euros_comme_Estonie_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='finlande'), 'Services sociaux et de santé', 400000, 'automne 2023', 4.6, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='finlande'), 'Première loi finlandaise sur la conservation de la nature', 400000, 'Printemps 2023', 4.6, 'https://monnaies-euros.com/images/2euros_comme_Finlande2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='france'), 'Coupe du monde de rugby France 2023', 15000000, 'Juin 2023', 2.2, 'https://monnaies-euros.com/images/2euros_comme_France_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='france'), 'Jeux Olympiques de Paris 2024 - Semeuse', 260000, 'janvier 2023', 16.0, 'https://monnaies-euros.com/images/2euros_comme_France2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='grece'), '100e anniversaire de la naissance de Maria Callas', 750000, 'Juillet 2023', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Grece_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='grece'), '150e anniversaire de la naissance de Constantin Carathéodory', 750000, 'Juillet 2023', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Grece2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='irlande'), '50e anniversaire de l''adhésion de l''Irlande à l''Union européenne', 500000, 'Juillet 2023', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Irlande_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='italie'), 'Centenaire de l''armée de l''air', 3000000, 'janvier 2023', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Italie_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='italie'), '150e anniversaire de la mort d''Alessandro Manzoni', 3000000, 'janvier 2023', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Italie2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='lettonie'), 'Le tournesol ukrainien', 415000, 'mai 2023', 3.7, 'https://monnaies-euros.com/images/2euros_comme_Lettonie_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='lituanie'), 'Ensemble avec l''Ukraine', 500000, '1er trimestre 2023', 3.4, 'https://monnaies-euros.com/images/2euros_comme_Lituanie_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='luxembourg'), '175e anniversaire du Parlement luxembourgeois', 500000, 'février 2023', 6.5, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='luxembourg'), '25e anniversaire de la participation du Grand-Duc Henri au Comité international olympique', 500000, 'février 2023', 6.5, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='malte'), '550e anniversaire de la naissance de Nicolas Copernic', 95500, 'Juin 2023', 25.0, 'https://monnaies-euros.com/images/2euros_comme_Malte2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='malte'), 'L''arrivée des Français à Malte en 1798', 82500, 'Juin 2023', 30.0, 'https://monnaies-euros.com/images/2euros_comme_Malte_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='monaco'), 'Centenaire de la naissance du prince Rainier III', 25000, 'juin 2023', 360.0, 'https://monnaies-euros.com/images/2euros_comme_Monaco.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='portugal'), 'La paix', 1015000, 'novembre 2023', 2.6, 'https://monnaies-euros.com/images/2euros_comme_Portugal.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='portugal'), 'Journées mondiales de la jeunesse', 1015000, 'juillet 2023', 2.6, 'https://monnaies-euros.com/images/2euros_comme_Portugal2.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='saint-marin'), 'Les 500 ans de la mort de Perugino (le Pérugin)', 56000, 'avril 2023', 45.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='saint-marin'), '500e anniversaire de la mort de Luca Signorelli', 56000, 'Septembre 2023', 45.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='slovaquie'), '100e anniversaire de la première transfusion de sang en Slovaquie', 1000000, 'Mars 2023', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='slovaquie'), 'Bicentenaire du premier service de courrier express par véhicule hippomobile entre Vienne et Bratislava', 1000000, 'octobre 2023', 3.4, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='slovenie'), '150e anniversaire de la naissance de Josip Plemelj (mathématicien et astronome)', 1000000, 'décembre 2023', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Slovenie.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=0), (select id from countries where slug='vatican'), '150e anniversaire de la mort d''Alessandro Manzoni', 82500, 'Mai 2023', 32.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican2_2023.webp'),
  ((select id from commemorative_sets where year=2023 and name is null and sort_order=1), (select id from countries where slug='vatican'), '500e anniversaire de la mort de Pietro Perugino (dit le Pérugin)', 82500, 'Mai 2023', 30.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2023.webp');
