-- ============================================================
-- Import des 2€ commémoratives 2021 (31 pièces)
-- Aucune édition de la liste blanche cette année-là -> tout sur
-- des lignes génériques (jusqu'à 2 par pays -> 2 lignes).
-- Nécessite fix_and_import_2011_2017.sql déjà exécuté.
-- ============================================================

insert into commemorative_sets (year, name, sort_order) values
  (2021, null, 0),
  (2021, null, 1);

insert into commemorative_coins (set_id, country_id, name, mintage, issue_date, quotation, image_url) values
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='allemagne'), 'Saxe-Anhalt (série consacrée aux Länder)', 30000000, '26 janvier 2021', 2.2, 'https://monnaies-euros.com/images/2euros_comme_Allemagne_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='andorre'), '«Nous prenons soin de nos aînés»', 70000, '4e trimestre 2021', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre2_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=1), (select id from countries where slug='andorre'), 'Notre-Dame de Meritxell', 73750, '4e trimestre 2021', 20.0, 'https://monnaies-euros.com/images/2euros_comme_Andorre_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='belgique'), '100e anniversaire de la constitution de l''Union économique belgo-luxembourgeoise (UEBL)', 155000, 'été 2021', 10.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique2_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=1), (select id from countries where slug='belgique'), '500e anniversaire de la publication de l''ordonnance relative à la deuxie période d''émission de pièces de monnaie sous le règne de Charles Quint', 155000, 'automne 2021', 10.0, 'https://monnaies-euros.com/images/2euros_comme_Belgique_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='espagne'), 'UNESCO – Tolède', 4000000, 'février 2021', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Espagne_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='estonie'), 'le loup, animal national de l''Estonie', 1000000, 'automne 2021', 3.6, 'https://monnaies-euros.com/images/2euros_comme_Estonie_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=1), (select id from countries where slug='estonie'), 'Peuples finno-ougriens', 1000000, 'septembre 2021', 3.6, 'https://monnaies-euros.com/images/2euros_comme_Estonie2_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='finlande'), 'Le journalisme et la communication ouverte à l''appui de la démocratie finlandaise', 800000, 'printemps 2021', 4.4, 'https://monnaies-euros.com/images/2euros_comme_Finlande_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=1), (select id from countries where slug='finlande'), 'Centenaire de l''autonomie des îles Åland', 800000, 'automne 2021', 4.4, 'https://monnaies-euros.com/images/2euros_comme_Finlande2_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='france'), 'Jeux Olympiques de Paris 2024 - Marianne', 510000, 'septembre 2021', 12.0, 'https://monnaies-euros.com/images/2euros_comme_France2_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=1), (select id from countries where slug='france'), 'UNICEF', 7500000, 'mars 2021', 2.5, 'https://monnaies-euros.com/images/2euros_comme_France_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='grece'), 'Bicentenaire de la révolution grecque', 1500000, 'avril 2021', 3.0, 'https://monnaies-euros.com/images/2euros_comme_Grece_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='italie'), 'Les professionnels de santé', 3000000, 'janvier 2021', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Italie_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=1), (select id from countries where slug='italie'), '150e anniversaire de la proclamation de Rome en tant que capitale de l''Italie', 3000000, 'janvier 2021', 2.8, 'https://monnaies-euros.com/images/2euros_comme_Italie2_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='lettonie'), '100e anniversaire de la reconnaissance internationale de jure de la Lettonie', 412000, '1er trimestre 2021', 4.0, 'https://monnaies-euros.com/images/2euros_comme_Lettonie_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='lituanie'), 'Dzūkija (série consacrée aux régions ethnographiques de Lituanie)', 500000, '3e trimestre 2021', 3.6, 'https://monnaies-euros.com/images/2euros_comme_Lituanie2_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=1), (select id from countries where slug='lituanie'), 'Programme de l''UNESCO sur l''Homme et la biosphère – réserve de biosphère de Žuvintas', 500000, '2e trimestre 2021', 3.6, 'https://monnaies-euros.com/images/2euros_comme_Lituanie_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='luxembourg'), '100e anniversaire de la naissance du grand-duc Jean', 500000, 'janvier 2021', 6.0, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=1), (select id from countries where slug='luxembourg'), '40e anniversaire du mariage du grand-duc Henri', 500000, 'février 2021', 6.0, 'https://monnaies-euros.com/images/2euros_comme_Luxembourg2_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='malte'), 'Temples préhistoriques maltais de Tarxien (série consacrée aux sites inscrits au patrimoine mondial de l''Unesco)', 181000, 'Octobre 2021', 9.0, 'https://monnaies-euros.com/images/2euros_comme_Malte2_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=1), (select id from countries where slug='malte'), 'Héros et héroïnes de la pandémie', 72500, 'juin 2021', 60.0, 'https://monnaies-euros.com/images/2euros_comme_Malte_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='monaco'), '10e anniversaire de mariage du prince Albert II et de la princesse Charlene', 15000, 'juillet 2021', 450.0, 'https://monnaies-euros.com/images/2euros_comme_Monaco_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='portugal'), 'Participation du Portugal aux Jeux olympiques de Tokyo de 2020', 500000, 'mai 2021', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Portugal2_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=1), (select id from countries where slug='portugal'), 'Présidence portugaise du Conseil de l''Union européenne', 510000, 'janvier 2021', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Portugal_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='saint-marin'), '450e anniversaire de la naissance de Caravage', 54000, 'mars 2021', 55.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=1), (select id from countries where slug='saint-marin'), '550e anniversaire de la naissance d''Albrecht Dürer', 54000, 'août 2021', 55.0, 'https://monnaies-euros.com/images/2euros_comme_SaintMarin2_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='slovaquie'), '100e anniversaire de la naissance d''Alexander Dubček', 1000000, 'novembre 2021', 2.9, 'https://monnaies-euros.com/images/2euros_comme_Slovaquie_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='slovenie'), 'Bicentenaire de la fondation du premier musée de Slovénie, le musée régional de Carniole', 1000000, 'octobre 2021', 3.2, 'https://monnaies-euros.com/images/2euros_comme_Slovenie_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=0), (select id from countries where slug='vatican'), '700e anniversaire de la mort de Dante Alighieri', 86000, 'octobre 2021', 35.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican2_2021.webp'),
  ((select id from commemorative_sets where year=2021 and name is null and sort_order=1), (select id from countries where slug='vatican'), '450e anniversaire de la naissance de Caravage', 86000, 'juin 2021', 35.0, 'https://monnaies-euros.com/images/2euros_comme_Vatican_2021.webp');
